### ISSUE TITLE
Create Screens: lost password; resend confirmation email

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#10]
I put some placeholder text on the login page for these two screens, with two commented-out navigation links: https://github.com/bpoore/pbm-react/pull/7/commits/94d982fd70e5347bcf7f588e96d9f9eaa18ccc33

**Comment by RyanTG** [comment]
Waiting on https://github.com/scottwainstock/pbm/issues/1091

**Comment by RyanTG** [comment]
Update: Those endpoints are available now.

**Comment by bpoore** [comment]
These are ready to go: 64c331b0.

Wasn't sure if you'd prefer a back button at the top of the screen or to put buttons on the screen to navigate away. This currently has a `HeaderBackButton`.  We can change if you would rather have something else... we should have something somewhere so the user doesn't get stuck on the screen, but that could be buttons like the `Login` screen.

**Comment by RyanTG** [comment]
At first I was thinking of having buttons on the screen, and making cool backgrounds for these pages similar to the signup and login pages. Buuuuuuuuuut... now I think it's fine to just use the HeaderBackButton. These pages won't be used that much, and so it's probably not worth the effort of making sweet background images.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/162
