### ISSUE TITLE
In Location Details, show location name in header

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#11]
Instead of "Location Details" in the header, show the location name. If the name doesn't fit, cut it off with ellipses.

**Comment by bpoore** [comment]
Found the fix for this and applied it to signuplogin, signup and login. Styles will need to be updated with this new discovery. Leaving issue open until styles can be updated from this change. We can have the background image taking up the entire screen and move the content down or move everything down.

**Comment by bpoore** [comment]
The data is now there in the header. I did not style for cutting off with ellipses as I'm not sure how big the field should be. I removed the breadcrumb text to allow for more room for a longer location name, now it is just a back arrow. 
<img width="300" alt="screen shot 2018-08-10 at 6 05 13 pm" src="https://user-images.githubusercontent.com/7720282/43986589-0063a566-9cc8-11e8-94af-9eddc3d606a8.png">

**Comment by RyanTG** [comment]
Awesome! I use an iPhone SE, which is pretty micro, so it’ll be
interesting to see how that compares to your screenshot.
I’m hoping we don’t have to hardcore a width in there. But instead can
just say something like, width is 100%, and “if x overflow, then
ellipses.”

On Fri, Aug 10, 2018, at 6:05 PM, Beth Poore wrote:
> The data is now there in the header. I did not style for cutting off
> with ellipses as I'm not sure how big the field should be. I removed
> the breadcrumb text to allow for more room for a longer location name,
> now it is just a back arrow. screen shot 2018-08-10 at 6 0…> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/bpoore/pbm-react/issues/11#issuecomment-412240166

**Comment by bpoore** [comment]
c8ba32172a9a7909efac286fe3f76c862d3f63f3

**Comment by bpoore** [comment]
I see what's going on. We can leave this issue open until I get this fixed. Thank you for catching this!

**Comment by RyanTG** [comment]
Sweet!

**Comment by RyanTG** [comment]
As you can see in this vid, the name cuts off pretty quickly https://www.youtube.com/watch?v=I0unyNHrs7I

Could be a little wider. But we also want to leave space on the right for an "edit" button.
