### ISSUE TITLE
If you backspace out of the Autocomplete, it lists all locations

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#113]
Like, if you start typing in the searchbar autocomplete, such as "Ground", but then you backspace and delete the word. The autocomplete list doesn't disappear. Instead it shows all locations.

**Comment by RyanTG** [comment]
I'm only able to reproduce this on ios.

**Comment by bpoore** [comment]
38a87cfb01edf9dc1bf3a15eaeea77e9551b6da1 takes care of this bug. Overall, we should probably include throttling and debouncing here as well. 

For future reference: 
https://www.peterbe.com/plog/how-to-throttle-and-debounce-an-autocomplete-input-in-react

**Comment by RyanTG** [comment]
Yeah that sounds good. It definitely seems to be doing more lookups than necessary.

Thanks for knocking out that backspace issue!

**Comment by bpoore** [comment]
The number of lookups from what I can tell is fixed with the newly merged search modal work where we are waiting to perform a lookup until there's a pause in typing. Search is still an ongoing process, but I think we can close the autocomplete issue now. What do you think @RyanTG?

**Comment by RyanTG** [comment]
Yeah, seems good!
