### ISSUE TITLE
New picker/dropdown

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#117]
We don't like the native iOS picker, because it's always open and it's ugly.

But, trying out another option is beyond my skills (all the examples use arrays in the component section... and I'm confused). 

Some examples: 

https://github.com/peacechen/react-native-modal-selector
That one looks kinda like the iOS ActionSheet - seems active.

https://github.com/alinz/react-native-dropdown
Simple one. Not updated in a while. Might be more current forks.

https://github.com/sohobloo/react-native-modal-dropdown
This one is kind of loco-looking in the example gifs. Lots of options. Dunno if it's more complicated to implement. Has the most stars.

https://github.com/toystars/react-native-multiple-select
This one has a search function and seems pretty dang cool.

**Comment by bpoore** [comment]
The last one is really cool! I've been messing around with trying to get it in our repo, but I can't get their icons to play nice with our expo setup. Grrrr..

The first one is similar to what I already built for the add machine to location modal. I might try to replicate that flow for location type and operator and end up with a mix of the first and last ones on the list here without having to bloat the repo with another 3rd party solution. What do you think?

**Comment by RyanTG** [comment]
Sounds cool!
