### ISSUE TITLE
Only show a limited number of Machines in location list and map infowindow

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#12]
If the infowindow showed ALL of the machines at a location, then it would often be too long to fit on the screen (or could have a scrollbar... which isn't the worst thing). I think the machine list in the infowindow should only show... 5 machines at most. And if there are more, it should say, "And x more machines". If that last part isn't easy/possible, then it could say, "Plus more!" or "Plus more! x total machines"

And same for the location list. I think it's ok for people to click into the location details to see ALL the machines. Showing a truncated list makes the browser experience a little simpler.

(and so so far the infowindow and the location list seem to be using the same info... it's just the style that will differ a bit).

**Comment by bpoore** [comment]
I agree and it will be easy to have the 'and x more machines' since we have the machine count available. I just haven't gotten around to this specifically yet, so thank you for making an issue to explicitly track this task!

**Comment by RyanTG** [comment]
Cool. I figure some of the issues here will be duplicates of things on the ppt. In fact, I was thinking of going through the PPT, and translating it into issues (including screenshots of the mockups). Seems like it would be easier to track progress that way.

**Comment by bpoore** [comment]
25c9f6cef447edb3b8628f8c84e13d96e24f72f7
