### ISSUE TITLE
Misc design notes

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#121]
- [x] Work more on the edit location info page. HR separators? Slightly different colored backgrounds for each one (like grey/white/grey/white/grey/white).
- [x] Further design work for the location Info screen. HR or staggered color backgrounds?
- [x] Similar to google maps: show location type, then a separator, then miles away. So like “Bar - 3 mi”. 
- [x] Lighter grey text on those meta elements. 
- [x] background color on "location suggestion received, thanks" and update the text.
- [x] Recent activity is now set to 30 miles.
- [x] Search bar is cut off by notch.
- [x] Cancel button on suggest location preview is cut off at the bottom. Probably has to do with padding up top.
- [x] Vertically-align high score and comment input pages.
- [x] Update recent activity colors.
- [x] Add checkmark icon to Confirm button, and doublecheck wording.
- [x] Loading... is in middle of map (below my-location) on android.
- [x] The area to the right of my-location is unclickable.
- [x] Update the colors on the searchbox in FindMachines
- [x] inputbox radius changed to 50, backgroundcolor and bordercolor the same light gray.
- [x] Are there number commas in the "your highest score" value?
- [x] Reset/resend make sure keyboard closes on back. 
- [x] Splash image on android is small
- [x] Header titles are left-aligned in Android
- [x] X button on filter modal is cut off on Android
- [x] Fix dropdown style on Android
- [x] Add Patreon logo to About page (look into whether the iOS app store doesn't like patreon)
- [x] Sort the links in the side menu
- [x] Add note about Privacy Policy on About page and link to FAQ
- [x] Add question about machine versions to FAQ
- [x] Look into whether android phones have notches, too, and we need to account for that.
- [x] Patreon image is really small on android.
- [x] Move the "My Location" button on map from upper left to lower right.
- [x] ~Attempt to fix size of splash image on Android.~
- [x] Bottom border on machine score container seems to be missing (possibly only missing when there are no scores).
- [x] FAQ - “How do I get listed as an operator?”
- [x] location list and saved bottom margin is wrong
- [x] Profile, say “Locations Edited (up to 50)”
- [x] Add more space for "List"
- [x] Check on the vertical alignment of "City, Address, Location"
- [x] Check notch and tabbar on XR, and make sure search box doesn't shift up/down when clicked on.
- [x] Map icon is different in right menu and tabbar.
- [x] Direction buttons - move to right and make sure address doesn't overlap.
- [x] Vertically align the add machine confirm modal, similar to the add score and add comment modals. 
- [x] Add more space between the items on the Filter page.
- [x] I think the background image on the landing page has a gap up top.
- [x] Infowindow in dark mode has light text when the place has 1 machine. 
- [x] In light mode, section headers on profile page is too dark. 
- [x] Revisit button style. Consider dropshadow. On locationDetails, maybe the two buttons can be next to each other instead of on top. Bolder blue color in light mode?
- [x] Android - infowindow right-arrow needs repositioning
- [x] Android - check on positioning of X on MOTD and Filter Recent modals
- [x] MOTD header - more blue, less grey

**Comment by RyanTG** [comment]
Similar to google maps: show location type, then a separator, then miles away. So like “Bar - 3 mi”. 

Lighter grey text on those meta elements.

**Comment by RyanTG** [comment]
I should just keep this open, so I can keep writing notes to myself.

- background color on "location suggestion received, thanks" and update the text.

**Comment by RyanTG** [comment]
@bpoore Wonder if we need to do something like this to deal with the iphone X notch https://www.bram.us/2018/02/20/react-native-and-iphone-x-safeareaview/

**Comment by RyanTG** [comment]
More notch ideas: https://stackoverflow.com/a/55017347
`StatusBar.currentHeight`

or https://github.com/rebeccahughes/react-native-device-info

**Comment by RyanTG** [comment]
Notch notes:

Looks fine on XR, big margin on X simulator:
````
height: getStatusBarHeight(false) + 30,
paddingTop: getStatusBarHeight(false)
````

Unknown on XR, smaller margin on X simulator, but still too big. Unknown how the search bar looks on X:
````
paddingTop: getStatusBarHeight(false)
````

Unknown on XR, even small margin on X simulator, but the vertical alignment isn't perfect. Unknown how the search bar looks on X:
````
height: getStatusBarHeight(false),
paddingTop: getStatusBarHeight(false)
````

**Comment by RyanTG** [comment]
Try ‘react-native link’ to fix device-info error

**Comment by RyanTG** [comment]
I want to synthesize my thoughts regarding the current status of the notch. The notch is probably not resolved yet, given that 1) it looks wrong on the simulated iphone X, and 2) we don't know yet if Android notch phones need additional work.

We are currently using the https://github.com/ptelad/react-native-iphone-x-helper module, which identifies notched devices based on the screen resolution. This feels like a blunt and potentially problematic way to identify notch devices. And it will require updated code when new phones come out. It also doesn't account for notched Android phones.

When we use it, we are instructing, "if notched iphone, then make the header this height and give it this top margin. Same for the footer."


Another option to test/consider is https://github.com/react-native-community/react-native-device-info
This component identifies notched phones based on the device name. So again, it is an evolving list of phones that will require updated code as new phones come out. But the device list includes Android phones. The module _looks_ to me like a really big module, and we'd only be using one component of it. I'm not sure if that's undesirable.

The logic will basically be the same as the first module mentioned.


The final option is to use SafeAreaView. However, this wasn't functioning correctly with our React Navigation setup. And as of this writing SafeAreaView is iOS-only!

**Comment by RyanTG** [comment]
Latest Notch status: After evaluating the above ideas, I went with something entirely different! Still unsure how well it works with notched Androids. But it will be simple to adjust.

Basically, we look at the height of the device's statusBarHeight, and if it's greater than 40, then we assume it has a notch, and we pad accordingly.

````
    backgroundColor:'#f5fbff',
    height: Constants.statusBarHeight > 40 ? 60 : Platform.OS === 'android' ? 56 : Platform.OS === 'ios' ? 44 : null, 
paddingTop: Constants.statusBarHeight > 40 ? 30 : '',
````

This is a very simple method that doesn't rely on big libraries. Time will tell how accurate it is, but it seems ok right now.

**Comment by RyanTG** [comment]
````
"backgroundColor": "#000000",
"image": "./assets/splashmdpi.png",
"mdpi": "./assets/splashmdpi.png",
"hdpi": "./assets/splashhdpi.png",
"xhdpi": "./assets/splashxhdpi.png",
"xxhdpi": "./assets/splashxxhdpi.png"
}
},
"description": ""
}
}

I followed:
[dpi:(expected)]

mdpi: (640x960)
hdpi: (252x450),
xhdpi:(336x600),
xxhdpi: (504x900),
xxxhdpi: (672x1200)
````

**Comment by metroshica** [comment]
Weighing in on the Android notch notes here since I use a Pixel 3 XL which has the notch. Overall the app looks good, but the login screen needs to be adjusted. The background image goes into the notch area and has a blank area below the image. Took a screenshot but apparently Android doesn't show the notch in screenshots. You can see how the image is raised incorrectly though and I guess you'll have to use your imagination to envision the notch at the top until I can get another phone to take a picture of my Pixel 3 XL.
![Screenshot_20190609-234139](https://user-images.githubusercontent.com/7684916/59177423-ec32ca80-8b10-11e9-98ef-269c9ad64d32.png)

**Comment by RyanTG** [comment]
Thanks. I’ll make that image longer. I was sort of flying blind when I first made that graphic over a year ago.

**Comment by RyanTG** [comment]
@metroshica taller assets here https://github.com/bpoore/pbm-react/pull/219/commits/f148834c3f072bede59e573b8e0d832f94766ea0

Let me know if that looks better! Looks fine on my dinky iPhone SE.

**Comment by metroshica** [comment]
Should've responded to this earlier but the gap is still there for the Login screen on my notched Pixel 3 XL. Might want to open a new issue since this one is already closed.

**Comment by RyanTG** [comment]
Thanks for the update. Hmm. Man, how big does that image need to be? https://github.com/bpoore/pbm-react/blob/f148834c3f072bede59e573b8e0d832f94766ea0/app/assets/images/pbm-fade-tall%403x.png

Or, something else is afoot. Can you see in the expo log if it's loading the @3x asset, or a different scale?

**Comment by RyanTG** [comment]
Note to self: update the FAQ to include question about the Location List not showing locations outside the map extent. And there was one other thing I wanted to add to the FAQ... I'll edit this when I remember it.

**Comment by RyanTG** [comment]
Check out the Animated API https://docs.expo.io/versions/latest/react-native/animated/
https://docs.expo.io/versions/latest/react-native/animated/
https://www.youtube.com/user/wcandill

Not sure what we should do with it. But it's something to look at. [Example](https://reddit.com/link/epwzuk/video/xyzcw0b5gab41/player) (the waves are json).

**Comment by RyanTG** [comment]
I might try a slightly darker dark theme background. https://www.0to255.com/2a211c
Such as #16110e or or #201915

**Comment by RyanTG** [comment]
- when adding a machine, type in text and then if you scroll to see results that are under the keyboard, the keyboard isn’t dismissed. Need to check on the dismiss functionality there.

**Comment by RyanTG** [comment]
Maybe the “(City)” “(Region)” text in the autocomplete should be green or something. Like


![](https://i.redd.it/vxct0edab8o51.jpg)

**Comment by RyanTG** [comment]
Ideas gathered while considering some design updates:

- On map filter, pull out and highlight a couple location types (all, bar, retail store, more).
- On location details, put map in container with margins. But don’t include the full header above it (just the back arrow) - instead the map should be near the top.
- In fact, a few pages don’t need a big white header. Including map.
- On location details, would be cool to associate an icon with each location type.
