### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#133]
Error:
````
Invariant Violation: 1203,RCTView,11,[object Object] is not usable as a native method argument
````

Steps:
1. be logged out
2. go to location details of a location
3. click the "login to add machine" button
4. login
5. when you press the "login" button it errors.

This can also be replicated by logging in from the "login to add machine comment" and "login to add high score" button. And maybe more - I didn't try them all.

**Comment by bpoore** [comment]
I think this takes care of it. It took forever to figure out and still doesn't really make sense to me. 205ece9c8d8debd933abc6076bf64a8abb5fa200

**Comment by RyanTG** [comment]
Huh, strange!
