### ISSUE TITLE
Machine picker on suggest location - add “done” button after 1 has been selected

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#142]
Right now on the machine picker screen, there’s just a “back” button. I worry that users might not realize that pressing this will retain the list of machines they’ve picked (since “back” can be somewhat akin to “cancel”).

So maybe: in the right header, make a “done” button appear after the first machine is selected (could be grayed out before, or not visible at all). Clicking it does the same thing as the back button.

**Comment by RyanTG** [comment]
Or the "Back" button could magically change to "Done" if a machine is selected.

**Comment by bpoore** [comment]
It could use some style:
a744c9618ebc5d37b5ed91b51f5e63d639f0bdcb
