### ISSUE TITLE
Geocoding on Search

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#150]
If a user types something, and they don't select an autocomplete, when they hit the "return" key on their keyboard, their string will be geocoded.

_Beth noted:_ It would be amazing if we could use geocoding autocomplete, but I don't think we can swing that.
_Ryan replied:_ We potentially could with Google Places. but it would duplicate our City autocomplete sometimes.

**Comment by bpoore** [comment]
🎉 89e5b5814bc4a6712f536ed51d3482ee3dd0f904

In order to not allow the user to search until autocomplete has failed, the button turns into a search button after no results come back for autocomplete.

**Comment by RyanTG** [comment]
This seems pretty cool. I think we'll have to wait for beta to see if users dislike requiring the autocomplete to fail before being able to do a geocode search. I wasn't thinking we'd do it like this. But I think it's something that needs the opinion of the masses.

I definitely don't mind it so far!

**Comment by bpoore** [comment]
I thought we were worried about the cost of running unnecessary geocode requests. We can certainly have this be set up to run search at any time in the process- I was just under the impression this was the most affordable approach.

**Comment by RyanTG** [comment]
True. At this point we don't know what our costs will be! So, it's smart to be conservative.
