### ISSUE TITLE
Don't show "enable location services" screen if permission is enabled

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#151]
If you logout, then close and reopen the app, you'll get the "enable location services" screen every time, even if you've previously allowed that permission.

We should only show that screen for first time users, and for those who haven't enabled the permission yet.

**Comment by RyanTG** [comment]
In more detail:

FIRST Time user will see when they first open the app:

- enable location screen, then
- signuplogin screen

After that, it they reopen the app, it goes straight to the map (totally skipping enable location and signuplogin, even if they have location services turned off and/or aren't logged in). (does this help setting up that one-time message? https://medium.com/technoetics/creating-first-time-user-welcome-screen-in-react-native-42f08cb0ebbe)

If they do not have location services enabled, then if they click the "my-location" button on the map, then it will prompt them to enable location servies.

**Comment by bpoore** [comment]
I believe this follows the desired outcome you described: 722704eb2d483bc684655beb07938f333f1751d8

FYI, every time I wipe out my simulator, it asks if I want to enable location tracking, so I'm not sure we need the enable location screen? 
<img width="388" alt="Screen Shot 2019-04-06 at 2 05 12 PM" src="https://user-images.githubusercontent.com/7720282/55675275-164be000-5875-11e9-8e03-7c64d6024d83.png">

I don't know how to clear asyncStorage on the actual phones when testing with them to see what happens with them :<

**Comment by RyanTG** [comment]
I never really thought we _needed_ that screen - I just thought it was a nice thing to have.

I’ll check this!

**Comment by RyanTG** [comment]
On Android, I don't get the enable prompt when I click the my-location button. I get this instead:

![Screenshot_20190406-212729](https://user-images.githubusercontent.com/632682/55678713-1bc81b00-58b3-11e9-8fa4-db8eaeb42f9b.png)

**Comment by bpoore** [comment]
I spent a fair amount of time working to try to figure out how to figure out how to get the prompt to show up to the user to actually change that setting and didn't end up being successful. 

I went through some tutorials and read the docs about Permissions and Location here: https://docs.expo.io/versions/latest/sdk/permissions/#permissionsaskasynctypes, so true, we don't yet have a way for the user to enable permission from within the app. At this time they are alerted to make those changes and are forced to go enable the permissions themselves. This is something I can continue to look into more.

**Comment by RyanTG** [comment]
Thanks for looking into it. In your screenshot, the prompt comes up on iOS as soon as the map is loaded?

In the android sdk, I know how to prompt a permission request when a user clicks something. But this is unknown to me in react native. 

Maybe we could just make that toast message more descriptive. Like “go to your setting and enable it” or something. Guessing we can’t include a link that goes directly to that OSs settings page..

**Comment by bpoore** [comment]
I figured out how to get to the app settings from within the app (`Linking.openURL('app-settings:')`), but I don't know how to check if they made a change to the preferences in order to do a request to find their location at some point after they open the settings from within the app.

**Comment by RyanTG** [comment]
I'll take a look at requesting permission. On Android, permissions are requested as they're needed. So there has to be a way to prompt the request when someone clicks that "enable location services" button. Something like https://stackoverflow.com/questions/49015539/react-native-android-how-to-request-for-permissions
