### ISSUE TITLE
LocationDetails - The "by" in Location last updated isn't showing up

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#153]
And I dunno why. Code looks ok to me!

It's showing "Last updated: Mar-30-2019 pbm" instead of "Last updated: Mar-30-2019by  pbm" 

https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L210

**Comment by bpoore** [comment]
There was a small typo in the variable: b0a838c55f275d03716299e3810cf8abbc93a413

Good catch. I imagine that's always been there.
