### ISSUE TITLE
Map icon in drawer menu isn't showing up

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#154]
https://github.com/bpoore/pbm-react/blob/master/app/screens/Map.js#L48

Also, the map entry in that menu is always highlighted, no matter which screen you're on.

**Comment by bpoore** [comment]
87b6cd8b823eb2ea00ea7c5422064822bf7786ad fixes the icon.

I've spent a lot of time looking into the highlighting of the screen you're on... no luck so far.

**Comment by RyanTG** [comment]
I thought we agreed `forgetabboutit`

**Comment by bpoore** [comment]
Most def. This is mostly a note to myself. It's amazing how easy it is to forget what's been tried / worked on / whatever.
