### ISSUE TITLE
Drawer menu

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#17]
Forgive me if we've already added a drawer menu package. ~~But this one looks legit: https://github.com/root-two/react-native-drawer~~ nevermind, it says front and center that the performance stinks. They suggest https://github.com/react-native-community/react-native-side-menu or React Navigation (which we already have... maybe this is the module? https://reactnavigation.org/docs/en/drawer-based-navigation.html).

This could be used for the hamburger menu (the menu icon will be in the lower left of the bottom navigation), with the money sliding in from the left.

It could potentially also be used for the FILTER screen (coming in from the right).

**Comment by RyanTG** [comment]
Contents of menu:

````
- Suggest Location
- Contact Us
- Store
- Blog
- FAQ
- Help
- Donate
- Podcast
- Logout (or Login)

**Comment by RyanTG** [comment]
@bpoore if we go with the new page option, then that’s something I can do. Seems easy.

**Comment by bpoore** [comment]
@RyanTG  I pushed up a first pass at the drawer navigation with the new pages. You can see it here: https://github.com/bpoore/pbm-react/tree/drawer-navigation. For the new pages, we should probably create a uniform header that will allow the user to either access the menu or back to the app more gracefully, but at least we have something for now!

**Comment by RyanTG** [comment]
CLOSING.
