### ISSUE TITLE
Zoom & How/When to Make Requests

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#176]
Currently, whenever a user moves the map, a new request is performed to get the locations for the new area. This does not work when the user is zoomed out farther than the maximum radius we are searching for locations. 

On the site, I see there is a button to select if you want to redo the map search on map position move and that the option is taken away if the user has zoomed out too far. What is the preferred scenario for the app?

Are we concerned we may be making too many requests to the API by requesting locations every time the map view is changed? (This is something we can work to optimize, but may require a fair amount of work)

**Comment by RyanTG** [comment]
My first thoughts are 1) We should increase the max radius, because that will make users happier, and if it becomes too much for the API we can re-evaluate it; and 2) When users zoom out too far, they should see a message that says, "Please zoom in to see results".

@scottwainstock Scott could answer the API request question better than I.

**Comment by bpoore** [comment]
Do we want to wipe out previously found results if they zoom out too far? Maybe we keep the most recent results seen with a message along the lines of "Zoom in to update results"? I'll work on getting that implemented and we can adjust if the radius can be increased. 

The current radius we're using is 5 miles, I see the API supports 50: https://github.com/scottwainstock/pbm/blob/master/app/controllers/api/v1/locations_controller.rb#L11

I supposed we can bump this up? I'm not sure why I originally had 5 in there... are we worried about the API server? With a 50 mile radius, I will feel more comfortable doing some basic math to determine when to request data again rather than requesting every time the map moves.

**Comment by RyanTG** [comment]
I'm for `keep the most recent results seen with a message along the lines of "Zoom in to update results"`

Bump it up!

Beta will hopefully give us at least some clue of the API server's ability to handle this.

**Comment by bpoore** [comment]
@RyanTG, now if you zoom out, the message is displayed. It is here if you have style ideas / preferences: https://github.com/bpoore/pbm-react/blob/master/app/screens/Map.js#L186

**Comment by RyanTG** [comment]
Sweet! I like it. And it's a big radius, so people will probably be happy. Hopefully the server is happy, too.

Feel free to close this if you're all done.
