### ISSUE TITLE
Update operator search to match find machine format

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#177]

**Comment by bpoore** [comment]
Wooo 8846014d50901799dd640aa5214c06112c14c893

**Comment by RyanTG** [comment]
I think you meant this: https://github.com/bpoore/pbm-react/commit/1566ebb1df31794778ef4732a1b0c57db5485e8e

I'll check it out!

**Comment by RyanTG** [comment]
Great!

I might explore whether we can give every other listitem a different background color. So like gray/white/gray/white. Not critical, but it might make these lists look more cool.
