### ISSUE TITLE
The "back" button sends you back to login or signup screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#18]
Steps:

- Do not login, instead click "skip this for now"
- that opens up the map
- Then click "profile" or "recent activity"
- Then click the back button in the upper left. 

Result: it sends you back to the login screen (or signup screen, if you had been on that when you pressed "skip").

Desired behavior: It should send you back to the map.

**Comment by bpoore** [comment]
How's this? dc567cdff5b0754c2614d6a4571acd81dcb1e622

**Comment by RyanTG** [comment]
Great!
I updated the titles https://github.com/bpoore/pbm-react/pull/20
