### ISSUE TITLE
No location name in header if you click from Recent Activity

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#180]
Steps:
- go to Recent Activity screen
- click an entry so you go to the Location Details screen

Result is that the location details screen doesn't show a location name in the header. I remember you noticed this, but I thought you resolved it. But maybe that was for when people click from the Location List?

**Comment by bpoore** [comment]
Oops. I thought this wasn't necessary after making some other changes. Added back in the logic to fix this. Recent activity keeps not being on my radar of things to think about because the simulator never has the location services turned on. Thanks for catching this! 18309983
