### ISSUE TITLE
Fix the Recent Activity sort order

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#189]
EDIT: original post removed. Updated for clarity.

The sort order of the Recent Activity items is wrong. I can't tell what it's doing (seems almost random!).

![Screenshot_20190505-140118_Pinball_Map](https://user-images.githubusercontent.com/632682/57233112-e0fcf400-6fd2-11e9-8cbb-ffaabad1dee5.png)

Once this is fixed, we may have to work on an issue related items not showing up in the feed right away (particularly, if they were made in other time zones).

**Comment by RyanTG** [comment]
Thinking about this more... This could be an issue related to the server time zone. The user who noticed this is in Austin.

1) I want to wait and see if it shows up.
2) If it is a server time zone issue, what changes would we need to make to the API?

**Comment by bpoore** [comment]
I will have to look at this more. I believe we were assuming the API was going to send us recent activity in chronological order. It's possible for the sorting to occur app-side, but I wonder if there is still some funkiness with this endpoint.

**Comment by RyanTG** [comment]
I don’t see this being sorted in the api https://github.com/scottwainstock/pbm/blob/master/app/controllers/api/v1/user_submissions_controller.rb

**Comment by bpoore** [comment]
It would be nice if it could come to the app in chronological order, but if that's not going to be the case, it can be sorted app-side. 

I thought this value was updated to be 30, https://github.com/scottwainstock/pbm/blob/master/app/controllers/api/v1/user_submissions_controller.rb#L20.

We can pass 30 in here as the max_distance, but I'm not sure if it will work as the max distance has been declared as 5.

**Comment by RyanTG** [comment]
Oh uh, hmm. I think I only updated this “max miles” distance https://github.com/scottwainstock/pbm/blob/eed75b3f8e10751fdd6cbf7b45933e87e59264a3/app/controllers/api/v1/locations_controller.rb

Which is for a different function. So yeah, let’s update that to 30!

And I’ll create a pbm issue to sort the user submissions.

**Comment by RyanTG** [comment]
I think I’ve confirmed that we still have a time zone issue. Or at least, an issue with submissions not immediately showing up in the feed, whatever the cause. I confirmed this by adding some machines in the Los Angeles region, and they still haven’t shown up in the feed.

**Comment by RyanTG** [comment]
Pbm issue.
