### ISSUE TITLE
Can the Events radius be adjusted by the user?

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#191]
I think the 50 miles is hardcoded in the PBM api....? I need to doublecheck that.

We've had a request that it be an adjustable number, like it is on the IFPA website, with set choices: 50, 100, 150, 200, 250.

**Comment by bpoore** [comment]
We can do that, yes. I think it makes sense to default keep the original value to search for at 50 miles to save on the size of data in the request and time for the request to come back, but we could definitely make options to bump up the search radius as you've described.

**Comment by RyanTG** [comment]
I agree that we should default to 50 miles.

This beta is cool because we get to learn how people in different areas use the map. It's not all urban users, with a dense amount of locations in one spot.

**Comment by bpoore** [comment]
a347554436137a13e27b27e8fed5342cc383d6ae

Feel free to update styles as you would like. This is pretty cool... if you search for `Japan`, you get the `No Events` message, but if you bump up the radius you see events. On the flip-side, now you can see events clear up to Seattle while the map view is in Portland.

**Comment by bpoore** [comment]
I realize I wasn't very careful with my IFPA API key... I'm not too worried though, worst case is they'd shut off this key if something went awry. If we are to update the API key, it will be hidden in the future and not a concern.
