### ISSUE TITLE
Use a HEART map marker for Saved locations

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#198]
**Scenario:**

- You have a few locations in your saved list.
- You are browsing the map, and there are map markers on it.
- It might be cool if the markers for your saved locations were a _heart_ rather than the circle, so you can quickly identify which ones are your saved ones.

@bpoore Any idea how tough this would be? I would supply the icon.

(we don't have a map view that _only_ shows saved locations, right?)

**Comment by bpoore** [comment]
Great idea!

It will be easy to have a different icon for saved vs not saved. 

Currently we don't have a map view that only shows saved locations, but that too wouldn't be too hard to implement. Do you think that'd be an additional filter on the filter screen? Or a button on the map to turn off and on? Thoughts?

**Comment by RyanTG** [comment]
Either of those would work. But I think the tidiest and most intuitive place would probably be an additional filter on the filter screen.

**Comment by bpoore** [comment]
There's a placeholder file for the heart icon: 59ade43daba2b2503d6acabfc543da05432b4513

I'll work on adding the favorite location filter to the filter screen in the coming day or so.

**Comment by bpoore** [comment]
7876ca6f22ce9eb1c50d0179ad3cdf5c0097223b

Uses a button group to toggle between viewing favorite locations or not. I can help update logic if you'd prefer a different styling approach for the selection process.

**Comment by RyanTG** [comment]
And styling https://github.com/bpoore/pbm-react/pull/201
