### ISSUE TITLE
iOS - If you re-open the app after not using it for a while, the my-location button puts you at your old location

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#215]
Haven't tested if this occurs on Android. 

Steps:
- Use the app.
- Do something else for an hour or something. And go to a different physical location.
- Re-open the app.
- RESULT: the blue dot will show your current location, but the "my location" button will put you at/near the location you were at before.

**Comment by bpoore** [comment]
That makes sense with how we were tracking location before finding the slick location finding feature. I will update the button to use the proper coordinates now that we have a way to know what they should be exactly at any given time.

**Comment by metroshica** [comment]
Confirming this happens in Android as well.

**Comment by bpoore** [comment]
This should do it 633c0d18da3923e97bc505672713044d98a6d4a8. Won't be able to confirm until we release a new build, but this makes way more sense than what was there before.

**Comment by RyanTG** [comment]
At the baseball game yesterday I opened the app, and it immediately found me. Was smooth.
