### ISSUE TITLE
iOS-iPad - Navigation labels overlapping icons

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#217]
I don't have any other iOS devices to test, but on the iPad the labels of the navigation bar are overlapping the navigation icons.
![Image from iOS](https://user-images.githubusercontent.com/7684916/59008768-8f6da200-87e8-11e9-8374-39c6ab6c05ae.jpg)

**Comment by RyanTG** [comment]
Ah, thanks. I have an iPad I can test, too. I’ve just been lazy and haven’t used it with the app yet (and also dreading it being a can of worms).

**Comment by RyanTG** [comment]
Hmm. Looks fine on my iPad.

![IMG_0096](https://user-images.githubusercontent.com/632682/59084880-a1674780-88b1-11e9-9ff2-4bc32b5486e0.PNG)

The splash graphic looks awful, though.

**Comment by metroshica** [comment]
Interesting, I'll have to get the specs of my iPad. Heading out of town tonight so I can update when I get back on Friday.

**Comment by RyanTG** [comment]
Another user experienced this, too. 

Possibly need to do something like: https://stackoverflow.com/a/48709199

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/223/commits/4b74653befa2bc2ad9e6a860cbcabad6fe53620c

I'm kind of flying blind here. But I'll check on my ipad later and see if anything stands out.

**Comment by RyanTG** [comment]
I updated iOS on my iPad, and now I see the problem (and now I'm able to scan the QR Code in Expo!!!!).

https://github.com/bpoore/pbm-react/blob/ddab7e08938e0ed91a1d44aad3b20fb6de5f7ceb/app/config/router.js#L87

So simple, and yet so... an hour of my life.

Source: https://github.com/react-navigation/react-navigation/issues/2805#issuecomment-371128926
