### ISSUE TITLE
Text alignment issues on Map.js

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#222]
Issues with text not being vertically centered on header and footer. Text in search field not vertically in-line with rest of header:
![image](https://user-images.githubusercontent.com/7684916/59177587-67947c00-8b11-11e9-924f-36538d3b5769.png)

Text in footer not vertically centered with container:
![image](https://user-images.githubusercontent.com/7684916/59177636-84c94a80-8b11-11e9-9f38-6a9bfe351baf.png)

Tested on Pixel 3 XL.

**Comment by RyanTG** [comment]
On iPhones with notches, there’s a horizontal line at the bottom of the screen. And that’s why the bottom menu is positioned like you see here - so it can be above the line. If androids with notches don’t have that line, I can adjust.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/219/commits/e23baec0fe6b45b6071837a201bd24a3fa08e489
https://github.com/bpoore/pbm-react/pull/219/commits/2f3609585e7e2ba71f549640f16e3a31fdcbce44

Let me know how this looks.

A month or two ago, I went through many trials figuring out how to deal with the notch. You might have read the synopsis of my travails here https://github.com/bpoore/pbm-react/issues/121#issuecomment-484723401

It's such a hassle!
