### ISSUE TITLE
Android map is really slow when there are lots of markers

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#225]
Other people are experiencing this: https://github.com/react-native-community/react-native-maps/issues/2658

https://github.com/react-native-community/react-native-maps/issues/2575#issuecomment-439674608

Not sure if those solutions will work for us. There might be other Issues about it.

**Comment by bpoore** [comment]
The 2nd solution is interesting... I implemented a homemade version of it where there we check that the map hasn't moved in 200msec before updating the map locations. I used to have it at 500msec, but wasn't seeing a reason for it to be so long. Maybe bumping it back up would help.

**Comment by RyanTG** [comment]
I've subscribed to a few of these issues on RNM, in case more info comes out about them.
