### ISSUE TITLE
Machine select when keyboard is visible

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#226]
On machine select list, when keyboard is up and you click an item, it just closes the keyboard but doesn't select an item. So you need to click once to close and then click the item. Not ideal.

We've fixed this behavior on other screens (for example, if the keyboard is visible on the Contact screen and you click Submit, it actually submits.

**Comment by RyanTG** [comment]
Could not get this. It _should_ work, but it doesn't.

`keyboardShouldPersistTaps='always'` should work on ScrollView (and its children) and also on FlatLists. 

but it's not for us so I dunno.

https://github.com/facebook/react-native/issues/10138#issuecomment-363142814

**Comment by bpoore** [comment]
2c65c1a975c92f3dc6228bbbb6b04a70332b4ab5
Checked on iOS device and Android simulator. Seems to work!
