### ISSUE TITLE
Crashes in iOS 13

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#232]
A user reported

>  the app immediately crashes on iOS13. Can’t say for sure if it’s you or Apple. You’ve got a few months to figure out I suppose.

**Comment by metroshica** [comment]
I just had a coworker load up the app on iOS13 today on his iPhone without any issue. Once I get iOS13 on my iPad I'll give it a shot to see if I can confirm what he's seeing.

**Comment by RyanTG** [comment]
This the primary issue tracker https://github.com/facebook/react-native/issues/25181

**Comment by RyanTG** [comment]
@metroshica By any chance, has your coworker tried the latest version of the app with iOS 13? We're on a different version of Expo (33), which _may_ have resolved the issue.

Also, here's Expo's discussion. https://forums.expo.io/t/ios-13-compatability/24667/13

**Comment by RyanTG** [comment]
@metroshica Does your coworker want to beta test for iOS 13?
