### ISSUE TITLE
5.0.0 User Feedback

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#234]
We released the app on 6/17/19. Since then we have received feedback via [reddit](https://old.reddit.com/r/pinball/comments/c1yvae/we_completely_redesigned_the_pinball_map_app_demo/?st=jx3fi8e1&sh=2ec30ece), [Tilt Forums](http://tiltforums.com/t/pinball-map-open-thread/901/361), the contact form on the app, email, app reviews, and more. We'll use this Issue as a repository for a bunch of the feedback, just so we have it all in one place. For the feedback that we actually want to address, we can peel them off into their own issue.

**------------------------------------------------**

**- Notifications tied to activity feed**
-- Moved to https://github.com/bpoore/pbm-react/issues/199

**------------------------------------------------**

**- on the activity page, it would make it easier to read if the user name, game name, location name and comment were formatted differently by using a different color or bold formatting.**
-- My response: This data comes to us as a single string, so right now we can't pull it apart and format different parts differently.  

**- Ability to expand range of activity feed**
-- My response: Could be a good idea. Could be similar to the events radius toggle.

**- For some reason, the keyboard stays up even after I have logged in with the password button above it. If I click on the password button, the keyboard vanishes while iOS prompts me for my fingerprint to access site passwords. That allows me to see the selections at the bottom, but I can't actually use them because as soon as I hit cancel, the keyboard pops back up.**
-- My response: I added `KeyboardAwareScrollView` to login. I kind of don't think it will resolve this issue (which I haven't been able to reproduce - I guess I don't save my passwords in iOS, so I don't see that prompt).

**- if you could just make the address ‘clickable to copy’ it would allow me & others to use the GPS mapping software of our choice (Waze!).**
-- My response: the `selectable={true}` prop should work in <Text>... but it doesn't, and that seems to be a known issue. I tried two workarounds (wrapping it in TouchableOpacity, and wrapping it in TextInput, and neither worked).

**------------------------------------------------**

~~**- Possible password issues. Two users reported that their password worked on the website but not on the app. One noted that there was "no failed login message"**~~
-- DONE. https://github.com/bpoore/pbm-react/issues/238

~~**- Rural users are sad when they don't see a bunch of machines around them. There's some confusion about the List view being a reflection of what's currently on the map.**
-- Beth noted: We could do something that after the first map load, if there are fewer than X locations in the view, we bump the radius to 50 miles or something like that. 
-- Ryan thinks about that: I'm not convinced we need to accommodate this use case. I don't know if this is grounded, but I worry a little about server requests - grabbing extra data without the user explicitly asking for that data.~~
DONE. We adjusted the "zoomed too far" limit.

~~**- When filtering results by machine, a user expressed that he'd like the list to have only machines that are nearby (rather than a giant list with over 1,000 items).**
-- Beth noted: We could possibly make the opacity of a machine not in the area lesser than others in the list.~~
DONE. https://github.com/bpoore/pbm-react/commit/b2f1579079fa360e113846abc7f8194486e6f4ae

~~**- At the bottom of this screen on an iPhone X (and later) there probably should be a little more “buffer”/white space.  The black bar you see is what replaced the home button and a little more white space below it would probably be visually appealing.  Yes, I’m bitching about something so minor :-D   It’s very low priority.**~~
DONE

~~**- tapping the search bar and seeing search history would be helpful.**
-- My response: Yeah, that would be cool. Like, you see the last 5 or 10 things you've searched, and then they disappear once you start typing a new search.~~
-- Moved to https://github.com/bpoore/pbm-react/issues/241
DONE

~~**- Include a sort option for number of machines in the Location List.**~~
-- Moved to https://github.com/bpoore/pbm-react/issues/245
DONE

~~**- Include city name in location list**~~
DONE

~~**- i would like to be able to swipe from the left to go back from location back to list.**
-- My response: perhaps this would come with an upgraded React Navigation? Or maybe it's already possible~~
DONE

~~**- double tap and dragging up and down to zoom in and out like on google maps makes it easier to zoom with one hand. [example.](https://gizmodo.com/this-secret-google-maps-gesture-is-totally-brilliant-5993128)**
-- My response: Seems like this should already be built into Android, since that uses the google map. But might not be possible in iOS unless we specify google as the provider.~~
DONE

**Comment by metroshica** [comment]
Swipe gestures: Looks like this is possible with existing libraries - https://www.npmjs.com/package/react-native-swipe-gestures

Activity page highlighting - While the API returns a string, it's still a pretty set format if you know what type of update it is and you could split the string on known delimiter words. For example, comments are in the format: <username> commented on <machine> at <location>. They said: <note>. Keying off the delimiter words there wouldn't be too hard, though changing the api response for activity feed would be more ideal.

One finger zoom - Can confirm this works on Android. Definitely doesn't work on iOS though, seems related to not using Google Maps by default. Found another Google Maps-related bug on Android that I'll open an issue for.

**Comment by RyanTG** [comment]
React Navigation also seems to support gestures, but I haven't played with it. https://github.com/react-navigation/react-navigation/issues/1063
`gesturesEnabled: true`

(note: I know this is different, but we already allow swiping between tabs in tabnavigator, a la https://reactnavigation.org/docs/en/material-top-tab-navigator.html#swipeenabled )

**Comment by RyanTG** [comment]
> One finger zoom - Can confirm this works on Android. Definitely doesn't work on iOS though, seems related to not using Google Maps by default.

This is fixed by using `provider={"google"}`: https://github.com/bpoore/pbm-react/pull/230/files#diff-3ec503720df5c538f8122ffad4dbb882
I'm not opposed to that. Google Maps is a better map, in my opinion. That said, Apple Maps has some benefits: the callout bubbles kind of bounce when you open them, which is nice, and they have a radius on the edges. I tried to set a radius here, and while I succeeded, it ended up removing the arrow that points from the callout to the marker - and we can't have that. I'll try again later.

Using google maps also fixes the issue of the the callout jumping from one marker to another when markers are closely clustered. So that's really cool.

**Comment by RyanTG** [comment]
@bpoore Do you recall why you did this? https://github.com/bpoore/pbm-react/commit/3990cb16b28887e7f9dbd984a2a7139e5c581a65
Wasn't sure if there was a good reason for it. When I set it to `true` it doesn't seem to solve the issue of not being able to swipe to go back on the location details screen.

**Comment by RyanTG** [comment]
To follow up on that, at least in expo, I swear the map acts up when gestures are enabled. It doesn't add anything, but it makes some markers not display, and the location details screen seem slower.

**Comment by RyanTG** [comment]
Nevermind, `gesturesEnabled: true` does work. I was just doing my gestures wrong - you gotta swipe from the edge. So, let me know if we _want_ this disabled for some other reason.

**Comment by RyanTG** [comment]
I reverted back to the default map provider, because I fixed the callout triggering twice when markers are close together.
https://github.com/react-native-community/react-native-maps/issues/2410#issuecomment-414928209
**I still need to check and make sure that prop doesn't impact anything on Android.**

And apple maps simply works better in iOS. I think the lack of single finger double tap to zoom is a current bug that will hopefully be resolved soon. https://github.com/react-native-community/react-native-maps/issues/2670

**Comment by RyanTG** [comment]
So far, I'd say the most common misunderstandings are:
- People don't realize the Location List shows what is currently on the map
- People don't know that you search for machines by clicking Filter (and one didn't realize that after applying a filter, you then need to view the map to see the updated results).

Both of these could be solved with more information shared with the user - but that info would probably only need to be shared once. For example, I'm hesitant to display text on the Location List that says something like, "List of locations currently shown on the map", because that takes up space and once people learn it, it's not helpful to continue seeing it.

On the Filter page, we could move the "clear filter" button to the top of the list of filters. This would make it more obvious that they're _applied_ a filter (given that we don't make users take an extra step to apply a filter, and thus they might be confused about whether it's been applied). We could also have text that says, "View to map to see filtered results" or something.

In general, I dislike all these ideas.

**Comment by RyanTG** [comment]
```If i was going to request any features, i feel like sometimes the search doesn't automatically pull in the next nearest thing to you if it's a long way away. Having one big map is a big improvement from trying to decide which region to search in if you were between a couple before. But sometimes I'd like to see the nearest location even if it's 200 miles or something. It also seems like searching by name for a town doesn't always pull up the next closest location in that same way.```

**Comment by RyanTG** [comment]
Closing this. All the issues have been resolved, or there are separate open issues for them.
