### ISSUE TITLE
Second current location button appears on Android after using search

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#235]
I noticed that if I use the search functionality on Android, a second current location button pops up in the top right of the screen:
![Map](https://user-images.githubusercontent.com/7684916/59795553-bb812c80-9298-11e9-97f0-d3ebf0e48f2d.png)

It looks like it's a native functionality of Google Maps, as I've confirmed this doesn't show up on iOS. The button is functional and it actually has a nice, smooth panning animation that would be nice for the actual current location button. It also doesn't go away when you push it, so it sticks around on the map until you force close and reopen.

**Comment by RyanTG** [comment]
I noticed that, as well, but haven't had time to look into it. Thanks for making an issue.

Kinda strange that it shows up after a search, if you ask me. Quick initial search on https://github.com/react-native-community/react-native-maps/ isn't producing any results, but I'll check again later.

**Comment by RyanTG** [comment]
I think we need to add `showsMyLocationButton={false}` to the `<MapView...`

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/230/commits/4ec2a5f4a70de929b502d5ec52a6c6071df4c782
