### ISSUE TITLE
Password issues

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#238]
Peeling this one off into its own issue. 

It seems that passwords with certain special characters aren’t working & and % notably. Problem seems to be that the API is using GET. Possible solution is to use POST. 

Discussion ongoing in chat... just wanted an issue.

**Comment by bpoore** [comment]
Going to fix using encodeURIComponent(): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent 

No need to change the way the app interacts with the API.

**Comment by RyanTG** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by RyanTG** [comment]
For reference: https://github.com/bpoore/pbm-react/commit/08a43b798bbdbc7c0466b7db2261df2e9cb033cd

Should I test this? Or are we good to go here?

**Comment by bpoore** [comment]
I tested it. You can now have a password of `&&%%&&` with no problems.
