### ISSUE TITLE
If you pan the map while the map is "loading" it will jump back to the previous extent

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#239]
Just something I noticed:

- On the map screen, pan the map
- Before the locations load, pan it again
- Once it finishes loading it will jump back to where you were after the first pan

It seems like it doesn't like being interrupted.

**Comment by bpoore** [comment]
I've seen this with Android occasionally. I have an idea what's going on, but not sure of the effort level to fix. Will look into this.

**Comment by RyanTG** [comment]
I definitely see this with iOS. It makes it difficult to pan-pause-pan-pause-pan (say that I load Portland, but then I want to zoom out and pan over to Astoria, but I don't know exactly how far I need pan - so I pan a bit, then look at where I am, then pan some more).

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/compare/19ec8beebebc...3774290eea2f

Beth increased the wait time, and it mostly fully resolves the issue. Closing.
