### ISSUE TITLE
Filter autocomplete / dropdowns

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#24]
Thoughts on how these autocompletes / drop-downs should look and work?  I'm not sure about having two fields each for machine and operator, especially since only one for either can/should be selected at a given time. What do you think about an autocomplete field where the default blank input will show all machines or operators for if the user wants to scroll through everything?

<img width="589" alt="screen shot 2018-09-02 at 8 55 58 pm" src="https://user-images.githubusercontent.com/7720282/44966908-cbd73f00-aef2-11e8-9e6c-1660dccab51f.png">

**Comment by RyanTG** [comment]
I think that would be ok. 

But I’m less certain about the machine filter. Just because some people might be more comfortable using a drop down list. On the website, if a user chooses an autocomplete option, it magically populates the drop down with that value. So there’s never two different values in those fields. 

But anyway, let’s just do it as you suggested. If users complain, then we can reconsider.

**Comment by RyanTG** [comment]
This is somewhat  similar to our current iOS app dropdown/picker: https://github.com/nulrich/RCTAutoComplete

But this might be iOS only, and it doesn’t seem well maintained. 

On both android and iOS right now, there are two elements, an autocomplete, and a list. If you choose from the autocomplete, you then need to click an ADD button. If you choose from the list, you simply need to click the item in the list and it gets added. 

![8fcda8b6-2dd9-4752-82d9-1ad01b7beec3](https://user-images.githubusercontent.com/632682/46567858-f9e3e080-c8ef-11e8-8afc-0091a5f6f8f6.png)

**Comment by RyanTG** [comment]
I think I was describing this incorrectly.

What we have on iOS is more like a full list, coupled with a filter field. So you can either keep the filter field empty, and then scroll down the entire list to find the machine. Or you can type something in the filter field, and the list will then get filtered/reduced to match.

**Comment by RyanTG** [comment]
Possible option: https://github.com/hiddentao/react-native-modal-filter-picker

I don't love the idea of a modal, though.

**Comment by bpoore** [comment]
@RyanTG I've been working on basically this for when a user would like to add a machine to a location. I made a quick PR of what I have now... especially if you think this is heading in the wrong direction, I can stop working towards this as it is.

I'm basically working to implement a screen very similar to the current iOS app to search for a machine to add to a location. I was thinking for the user experience as well as code reuse, perhaps the same screen could be used to filter by machine as well. 

Thoughts? https://github.com/bpoore/pbm-react/pull/83

Again, this is pretty rough. It just so happens this is what I've been actively working on over the last day. I can focus on trying to find a dropdown option we are happier with if you don't like this approach.

**Comment by RyanTG** [comment]
@bpoore So, circling back to this. Now that the sweet AddMachine component is working, is there a way to insert it into this screen?

**Comment by bpoore** [comment]
We will need to make the component more generalized to use it for the filter screen, but now that we have the pattern down, if you like how that's looking and feeling, we can get it or something like it here!  For adding a machine, we're having the user search for the machine on an entire screen. It might be worth nailing down the desired UI before going to code for filter. Do you envision the search contents in a scrollview on this screen or to go with navigating to a full screen like we're doing for add machine?

**Comment by RyanTG** [comment]
I think for the filter by machine select, we should try to use something like the “add machine” select. So users can search or scroll for a machine.

And when they click a machine name it should select it and immediately take them back to the previous screen. So, no need to give them an extra “done” button. Unless it’s more work to do it like that...

**Comment by bpoore** [comment]
Good call. The FindMachine component is pretty flexible. We should be able to use it here as well.

**Comment by RyanTG** [comment]
Perfect!
