### ISSUE TITLE
Consider: increasing the "you zoomed out too far" limit when people are Filtering results

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#240]
When a Machine filter is in place (or any filter, for that matter), the data demands are always going to be much less than if there was no filter.

So, maybe we should allow users to zoom much further out if they have a filter in place.

**Comment by bpoore** [comment]
Sure. How far do you think? 200 miles? 250? Great idea.

**Comment by RyanTG** [comment]
I would say go even further (the website is currently capable of loading ALL locations with a particular machine, and it seems to be no problem) - BUT, the "two or more machines" filter will probably yield way more results than all the other filters. If we can add two steps to it: if filter is only "two or more machines" then 250 miles; but if the filter is anything else, then crank it up to 500 or even 1,000 miles.

**Comment by bpoore** [comment]
Word. I like it.

**Comment by RyanTG** [comment]
Also, I think we can increase the no-filter "zoomed out too far" extent. Let's take advantage of our beefier server.

**Comment by RyanTG** [comment]
Current max is `100ish miles`

Let's try these values:

Unfiltered: `200 miles`
"Two or more machines" filter: `300 miles`
Any other filter: `500 miles`

**Comment by bpoore** [comment]
Overall max zoom has been increased here: ac8fba5cdd407755f95674268a8f6175d2a36e51

It's a bit more work to get the 'by filter options' done... will get to that in the coming days. Wasn't sure about the release timeline... the overall max zoom was low hanging fruit.

**Comment by bpoore** [comment]
This should do it 046313db87d96951b43c93c1d0094cb90687ee87. I will test a bit more myself tomorrow just to make sure it's behaving as we expect it to. Should we potentially update the text in the case where a user has zoomed out too far, but could potentially zoom out more if they apply a filter?

**Comment by RyanTG** [comment]
I'm not sure if it's behaving as we expect it to. What I'm seeing:
No filter = 200 miles.
Filter 2+ machines = 300 (at least)
Filter anything else = 200 miles (seems the same as no filter).

I can play with it tonight. I also think I want to adjust the values.

**Comment by RyanTG** [comment]
I feel like an idiot, but I can't make heads or tails of this logic. It doesn't work as I expect when I tweak it.

For the distances, maybe this is better: `return filteringByTwoMachines ? 200 : filterApplied ? 300 : 150`
But it's hard to say until the filter is working right.

**Comment by bpoore** [comment]
There was something wrong, you're right! Believe it's fixed now. It should have been filterApplied is true when filtersNoMachines is true OR numMachines > 0... it was in there originally as &&. I believe I was only testing in cases where there was a numMachines filter being applied. Oops!

**Comment by RyanTG** [comment]
Ah ok. I swear I tried that. But I may have only tried it with a combo of other edits. I’ll doublecheck it at lunch.
