### ISSUE TITLE
Show search history in searchbar

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#241]
User feedback: It would be cool to see the last, say, 8 searches when you click on the searchbar. And they go away when you start typing (then reappear if you backspace out of your search string).

**Comment by bpoore** [comment]
That was some good feedback. 

We could set that up a few different ways. One would be that the API provides us that info (assuming the user is logged in) based on a request that is made when the search bar is pressed. Another way, which would be faster because there would be no request, but would be less persistent would be to save the requests in app state (which will go away if the app restarts) or local storage (how we check if the user is logged in when the app fires up). Open to a discussion about the preferred way to go. Local storage seems like it could be a good choice?

**Comment by RyanTG** [comment]
I agree that local storage seems like a good option.

**Comment by bpoore** [comment]
I've been working on this and I think it's going to be pretty cool. A couple things to think about came up as I started in on this. What I currently set up (and was the easiest to get started), is just straight up taking the typed query in the search bar and save that into their search history. With this set up, the user would press on their previous search content to kick off a query to obtain search results.

These images represent what the flow would be in this scenario: 
<img width="449" alt="Screen Shot 2019-07-06 at 10 02 01 PM" src="https://user-images.githubusercontent.com/7720282/60764187-c201f900-a039-11e9-9420-4de65c393568.png">
<img width="446" alt="Screen Shot 2019-07-06 at 10 02 41 PM" src="https://user-images.githubusercontent.com/7720282/60764190-cd552480-a039-11e9-88b3-67b5534deefa.png">


The possibly more natural way to do this would be to save the actual search option the user selected over time? This would be a fair bit more work / code, so wanted to circle back on how we want this to work. To capture the previous searches someone has done means we have to track the search string as well as the search type so we know how to direct their search upon pressing the ListItem.

So, the question is- do we want to track what the user has most recently searched for in the search bar or what they have most recently navigated to in their search?

**Comment by bpoore** [comment]
@RyanTG, if you'd like to check out https://github.com/bpoore/pbm-react/tree/saved-searches and see if you are into this / see anything buggy, that'd be sweet. Think it's ready to go depending on your feedback. Will hold off on merging to master until you get a chance to look at it.

**Comment by RyanTG** [comment]
Nice. I'll check it out tonight! Did you test on Android? If not, I'll check it out on all my devices.

**Comment by bpoore** [comment]
I looked at it with the Android simulator.

**Comment by RyanTG** [comment]
Works/looks great on my SE and Android. Should I also test on the XR? Overall I think it's GOOD TO GO. Awesome feature.
