### ISSUE TITLE
Region as a keyword search

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#242]
Thinking it could be nice to have the different regions show up if `region` is typed into search. This would allow users to browse regions more effectively and some region names are less obvious than others.

@RyanTG any opinion pro or con?

**Comment by RyanTG** [comment]
Yeah, that would be sweet!

And you're right - the region names are not super consistent (given that some regions are cities or states or countries.

**Comment by bpoore** [comment]
341a90591c9276f5e732d5517ab891a97c2639e1

**Comment by RyanTG** [comment]
Sweet!
