### ISSUE TITLE
Add Sort by Number of Machines to Location List

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#245]
SSIA

Commit with logic: a44e81f5f9b8b46377d40088b7574b8ee3b2deb7

Need @RyanTG, to check on updated wording on the buttons / give a look over that styling looks ok now that there's another button taking up space.

**Comment by RyanTG** [comment]
This is great - thanks! I don't _love_ "Updated" but I'm not sure how else to say that so succinctly.

**Comment by bpoore** [comment]
I hear you! I wasn't sure what to do, but we needed to trim characters wherever possible!

**Comment by RyanTG** [comment]
Agree. It fits on my iPhone SE!
