### ISSUE TITLE
Bug: When location has an operator, you can’t change it to N/A

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#246]
Steps: look up a location with an operator. edit the location and change the operator to N/A. Save and confirm.  Result: The operator is still listed as the operator.

**Comment by bpoore** [comment]
I looked at this. When updating a location_type or operator_id to be non-existent, we are passing `null` to the API. My impression was that passing `null` would allow the API to know to knock out whatever value had previously been in place before, but at this point in time, submitting `null` is having no effect on the value being passed and we are getting back the 'updated location details' where the location_type and operator_id are the same if you're trying to clear out either of those values.

**Comment by RyanTG** [comment]
If a location has a location_type, and on the _website_ you successfully change it to null, the app never picked up on that. The app will continue to show the previous location_type.

This indicates to me that the issue might not be only (?) with the API. It's either with both, or it's only with the app.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/409/commits/3f516c7842ada08f76b24e56fc10b378ca206d1a

Submitting an empty string instead of null. :shrug:
