### ISSUE TITLE
Upgrade Expo to 33

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#249]
Release notes: https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c?gi=f2d0fac7c96f

**Comment by RyanTG** [comment]
Note to self to try this: expo build:android --type app-bundle

Also, not bothering with the modular imports stuff. But that will have to be done for 34.

**Comment by RyanTG** [comment]
https://stackoverflow.com/questions/49311395/react-native-expo-font-loadasync-doesnt-load-material-icons
https://github.com/bpoore/pbm-react/blob/2f103918b7533ab7f87708f6cb736d0ff3b3abd0/app/screens/Map.js#L152

**Comment by RyanTG** [comment]
````

The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: MapView.

1. Add correct versions of these packages to your project using:

   expo install react-native-maps

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { MapView } from 'expo' -> import MapView from 'react-native-maps'
````

**Comment by bpoore** [comment]
But we started using the MapView from expo recently 😭

**Comment by RyanTG** [comment]
It works fine in expo 33. I think this is a warning for future versions.
