### ISSUE TITLE
Location Details "Machines" tab: various things

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#25]
- [x] For each machine, show most recent comment. Truncate the comment after 200 characters, if possible.
- [x] For those comments, include the date the comment was made. "Updated: Jun-16-2018 by {username}"
- [x] Show location last updated date: "Location last updated: Aug-26-2018 by {username}". And that value gets updated if someone updates the location.
- [x] Include a "Confirm location is up to date" button.
- [x] Show a Right Arrow next to the machine name that then navigates to a machinedetails screen.

**Comment by bpoore** [comment]
@RyanTG- do you want the 'Add Machine' button to remain where it is currently? If so, where do you want the 'Confirm Location' button (the add machine button is where the confirm location button is in the current phone app)? Do you want the machine details page to have a similar layout to the current phone app? We're about ready to get this all hooked up. Here's where we are now: 19f7f86c249a7e2ec85058b7534162bd247d9c43

**Comment by RyanTG** [comment]
I think we should leave the Add Machine button where it is (and I'll work on styling it a bit). I think that's more intuitive than having a + in the upper right.

So then, I think the "confirm" button should be placed below the "add machine" button. I'll style it differently, making it less intense than the add machine button.

I think the machine details page can more-or-less look like the current phone. Biggest difference is that right there are TWO machine screens on the iOS app, and for this app we want to consolidate all the info into one screen.

Android screenshot, for your records https://lh3.googleusercontent.com/LH1RTczduB78mYyTrEG4iuo5PXLxy8VUtbLiLA0MTV9BknEI25K4owrgyv7WptIijQ=w1471-h907

iOS screenshot: https://pinballmap.com/assets/app_support/iphone-v4-04-5287b394fc2b3f618206196d5a1a99d4e3ad1737f80bcbf107bca343af3edf0b.jpg

And here's all the content. I'll style this, and sort it). I like how the Android app has a red REMOVE trashcan in the header. It gives the user two options when they want to remove a machine.

```
Machine Name @ location name

Added to location: date

Machine condition (latest)

add condition (BUTTON)

Machine condition (past)

High Scores

Add Score (BUTTON)

Pintips link

IPDB link

Machine manufacturer and year

Remove machine

Find other nearby locations with this machine (how should we implement this? It could be a button that opens up the map to like 50 miles, only showing locations with that machine...)
```

**Comment by bpoore** [comment]
@RyanTG - this all sounds great. I'll get the location details wrapped up and get right into the machine details screen.

For the confirm location is up to date, do you want to retain the behavior that clicking the button immediately makes the API request or should clicking the button bring up a confirmation modal? For example, I accidentally claimed a location was up to date yesterday not realizing there wouldn't be a confirmation prior to sending the request. That might not be a frequent problem, but I was surprised. and wasn't able to undo.

**Comment by RyanTG** [comment]
We actually discuss this on the first episode of the podcast! My assumption is that people do indeed accidentally click that button. BUT, I'm ok with that, because I don't want to add a confirmation modal. 

If we sense that it's a real problem, then we can address it in the future.

**Comment by RyanTG** [comment]
Right now when I click the "confirm" button, the date doesn't change right in front of my eyes. I'm also not seeing a "thank you" flash message (I'm just seeing it in the log).

**Comment by RyanTG** [comment]
I'm going to close this, and I'll make new issues of the remaining things.
