### ISSUE TITLE
Filter to list only nearby machines

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#272]
- When filtering results by machine, a user expressed that he'd like the list to have only machines that are nearby (rather than a giant list with over 1,000 items).
-- Beth noted: We could possibly make the opacity of a machine not in the area lesser than others in the list.

**Comment by bpoore** [comment]
@RyanTG if this will work for now and you see it working properly (I checked, but am tired and will try again later), this can get merged to the dark-mode branch for the new release https://github.com/bpoore/pbm-react/pull/276
