### ISSUE TITLE
Location Details - make the whole page scroll

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#28]
Right now the little map and the "machines|info" buttons do not scroll. I think they should, since they take up a lot of real estate. 

I tried adding a <ScrollView>, in a few spots, but it always resulted in the little map disappearing. So now I'm making an issue!

**Comment by bpoore** [comment]
Curious. I'm seeing that too. 

I tried some of the suggestions found here, but haven't had any luck fixing this yet: https://github.com/mapbox/react-native-mapbox-gl/issues/997

**Comment by RyanTG** [comment]
I'll take another look.

This issue isn't a fix, but at least it has a code example. https://github.com/mapbox/react-native-mapbox-gl/issues/1044

**Comment by RyanTG** [comment]
This seems to do it. https://github.com/bpoore/pbm-react/pull/48/commits/54215ba74ab4f64d1456a23a0dc409df0a38c834
That diff looks way more dramatic than it actually was.

Only possibly downside is that the height of the map is hardcoded to 100 units. Not sure if that's ideal for all phones. But we can come back to it later.
