### ISSUE TITLE
Blue “my location” dot covers up location dot

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#287]
If you’re physically at a location, the blue dot covers up the location’s red dot. 

Possible solutions:
- Sort the red dots above the blue. 
- Make the red dots increase in size as you zoom in. 
- Make the blue dot smaller.

**Comment by bpoore** [comment]
I’m pretty sure our only option would be to increase the size of the red dot for this. The blue dot is coming from react native maps, I don’t think we have any options to customize it’s appearance.
