### ISSUE TITLE
On some iOS devices, the scrollbar is showing up in the middle of the screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#288]
If you click a location from the map, and that location has enough machines that you need to scroll to see them all, then the scrollbar is in the middle of the screen instead of on the far right.

The scrollbar issue doesn't show up if you bring up the locations details by directly searching for a place.

**Comment by RyanTG** [comment]
![image0](https://user-images.githubusercontent.com/632682/73127613-d37c0580-3f77-11ea-9912-be3e3279ae8e.png)
![image1](https://user-images.githubusercontent.com/632682/73127614-d4149c00-3f77-11ea-9020-52ab301b5fc8.png)
![image2](https://user-images.githubusercontent.com/632682/73127615-d4149c00-3f77-11ea-9131-8be35ed41990.png)

**Comment by bpoore** [comment]
I wonder if <a href="https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L255">this</a> should be wrapped in a ScrollView and if that would help. I will give it a shot.

**Comment by RyanTG** [comment]
I can test it in the XR once you have a branch.

**Comment by RyanTG** [comment]
Seems fixed!
