### ISSUE TITLE
Add logout button to profile screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#29]
When clicked, it directs the user to the login screen.

Once we have a logout button that works, we can better determine how the app will look/work when logged in or out (cuz right now it's confusing because I can't always tell if I'm logged in!). For example, I don't think we need to _hide_ all the logged in features (like `add machine`), but instead, if they're clicked while a user is logged out, we just redirect them to the login screen.

**Comment by bpoore** [comment]
That's a good idea. I wasn't sure if we were going to have a logout affordance for the app... I didn't realize the current app has one until I just looked at the profile page!

**Comment by RyanTG** [comment]
Yeah, it's definitely tucked away on the current app. And that's fine! We just want to have it _somewhere_.
