### ISSUE TITLE
Dark Mode Selection

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#291]
New screen allowing user to view / update theme preference.  Allow user to use theme different than their OS theme.

**Comment by RyanTG** [comment]
Thanks! I think I found an issue:

It doesn't matter which button you click - all of them toggle. For example, if you have the "dark" button selected, and then you click it again, it will toggle your theme back to standard (while still keeping the "dark" button selected). Does that make sense, and are you seeing that, too?

Maybe this is standard behavior for button group buttons?
