### ISSUE TITLE
Don't show login/signup if user is logged in

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#30]
The login/signup screen shows up no matter what. And if I'm already logged in, it allows me to login again!

**Comment by bpoore** [comment]
I agree this is something we need to change. If a user is already logged in, what is the first thing they should see? Should they be taken straight to the Map screen?

**Comment by RyanTG** [comment]
Yeah, I think straight to the map.

**Comment by bpoore** [comment]
Cool. I'm starting in on this. It will require moving a fair amount of stuff around, but it will be good to have this taken care of.

**Comment by bpoore** [comment]
9943325137eada6859cbf386021c4fe08cfc9228
A lot had to be moved around to do this, so I will continue testing and refining over the next couple days. Now- if you are logged in, you should end up going directly to the map and if you're not, you end up at the SignupLogin screen. **If you choose to not login, the next time you fire up the app, you are still brought to the SignupLogin screen (do you agree this is the desired behavior)?** Basically, if you have auth credentials, those are being persisted to the memory on your device- we are checking for those credentials when the app fires up. The credentials should remain on the device's memory indefinitely or unless they explicitly logout. 

**Upon logout, the user is not brought to SignupLogin. Is this desired?** 

I still need to add in the ability to Sign in if you chose to skip logging in. Up to you where to put that and what buttons should be visible logged in vs not.

**Comment by RyanTG** [comment]
Yeah, both of those are desired behavior.

> I still need to add in the ability to Sign in if you chose to skip logging in. 

Are you talking about a "Log In" link that goes back to the login screen? If so, see this Issue: https://github.com/bpoore/pbm-react/issues/17 That menu should include a "login" (or "logout") link.

> Up to you where to put that and what buttons should be visible logged in vs not.

I have some ideas, but haven't written them down yet. In the meantime, can you show me some generic code for this, in case I want to copy pasta?

Is it like:

````
      if (!auth && !this.props.user.loginLater)
        this.props.navigation.navigate('SignupLogin')
      else if (auth) {
        otherwise...
      } 
````
Because I can get started on added this, and similar, logic in places. For example, on the profile page, if you're logged in, you still see the Logout button, and you can then logout again!

So I just wanted to confirm that:
IF not logged in = `if (!auth && !this.props.user.loginLater)`
IF logged in = `if (auth)`

But maybe it's more complicated than that.

**Comment by bpoore** [comment]
@RyanTG, I'd eventually like to move away from using AsyncStorage every time we want to do anything related to auth credentials, but for now an example with the current code would be the buttons for the LocationDetails screen. 

We only care about the loginLater flag to get out of the loop of showing the user the SignupLogin screen when the app fires up and there are no credentials found in AsyncStorage. 

> Because I can get started on added this, and similar, logic in places. For example, on the profile page, if you're logged in, you still see the Logout button, and you can then logout again!

I thought I had fixed that, but looks like I missed something. It's fixed now with this: de36f58f9a3430b9646f7a7d07ddb7d57065f51d
This is an example of another reason why I'd like to move from AsyncStorage- we have 2 different places we have to worry about / check when dealing with auth right now. In this case, the user was logged out, but the Redux state hadn't been updated to reflect that.

**Comment by RyanTG** [comment]
Ok, I'll check those buttons on the locationdetails screen. I just foresee that I'm going to want to include "if logged in then THIS, if not then THAT" in a fair amount of places (we use it a lot on the website), and I don't want to burden you with it each time because it will get tedious.

**Comment by RyanTG** [comment]
What's the way to say "if logged out"?

userprofile uses this to say logged in: `{this.props.user.loggedIn &&...`
locationdetails uses this to say logged in: `{this.state.auth &&...`

Uses cases will be things like:

- when logged out, the profile page says something like, "Hi, login to have a profile. click here."
- and the location details page will show the add machine button, but when clicked it sends you to the login screen (could be a totally different, but similar-looking, button for this).

**Comment by bpoore** [comment]
@RyanTG, the last 3 commits I've made have fixed this up. Now, if you want to access information regarding the user's status, it will always be `this.props.user.loggedIn`. 

An example of if this then that:
` onPress={() => this.props.user.loggedIn ? this.props.navigation.navigate('AddMachine') : this.props.navigation.navigate('SignupLogin') }`

If at the bottom of the file, the user reducer isn't there, it will need to be added for the prop to be available. 

Example: 
`const mapStateToProps = ({ user }) => ({ location, locations, operators, machines, query, user})
export default connect(mapStateToProps)(LocationDetails);`

Let me know if you have any questions or see anything funky with this. Lots of moving pieces.
