### ISSUE TITLE
Larger map marker for spots with more machines

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#303]
Did we already rule this out, due to implementation issues?

**Comment by bpoore** [comment]
I thought it was due to the number of assets required as we are using an image currently. I will look into potential options... maybe we could use the same image but size it differently. If I recall, you generated the images we are currently using @RyanTG. I doubt it would be the end of the world to increase our app size if we want to include additional images in our bundle. I’m open and down to help with whatever I can!

**Comment by RyanTG** [comment]
Yeah, I generated those. It's very trivial to make a larger set. Plus, they're like 1kb each!

I'll make some, and then we can go from there. 

I think there should just be two tiers (or maybe 3?). Maybe, locations with 1-4 machines, and locations with 5+?

**Comment by bpoore** [comment]
@RyanTG, I've been playing with getting SVG images up and running in our project. There were a few extra steps than we'd need for web, but it looks like this might work! 

Adjusting fillOpacity: 
![IMG_5584](https://user-images.githubusercontent.com/7720282/93156830-c7d37f80-f6bd-11ea-84bb-466039a5079e.png)

Adjusting size:
![IMG_5585](https://user-images.githubusercontent.com/7720282/93157429-11709a00-f6bf-11ea-881d-9910cc300d28.png)

We can play with it more... we can adjust color values, size, opacity... whatever you like :)

**Comment by RyanTG** [comment]
I think a combo off opacity and size is a good idea!

What opacity are you using there? I think a little less transparent would be good?

And what size categories are you using? I think I see three different sizes there. First, I would go for a more subtle size difference between each category. 

And the categories could be:
1 machine 
2-4 machines
5-10 machines
11+ machines

**Comment by RyanTG** [comment]
Ongoing notes:

- Right now the icons get more intensely red when there are more machines. And I don't really like how it looks. Still working it out...
- Check into including a shadow
- Try light blue dots for dark mode. See how they look in light mode. Also consider orange.
- Look into making a simple SVG that includes a point (like a traditional map pin)
- Look into adding text showing number of machines (only when zoomed in a certain amount).

**Comment by RyanTG** [comment]
Trying a non-SVG approach, as documented here: https://stackoverflow.com/questions/40822129/airbnb-react-native-maps-custom-marker-with-centered-text-on-top

They even notes how to adjust the dot size based on zoom (something our current PNG does not do).

Things:
- How to give it a border
- Dropshadow
- Remove numbers when zoomed out far.

**Comment by RyanTG** [comment]
Just a note that we’re only using this on iOS.

I might revisit this to see if it’s worth removing the numbers when zoomed out far.
