### ISSUE TITLE
Status Bar color in dark/light modes

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#306]
Expo 38 introduced a new module called expo-status-bar. 

https://blog.expo.io/expo-sdk-38-is-now-available-ab6cd30ca2ee

https://docs.expo.io/versions/latest/sdk/status-bar/

https://docs.expo.io/guides/configuring-statusbar/

I think it would be valuable to use this. Currently in the app, if you are in dark mode in iOS, the status bar text is also dark, and you can't read it. I'm assuming that with this module we can make it so the status bar text is always a contrasting color.

@bpoore I've looked at these docs (though it's late and my brain is half asleep), and it's not clear to me if we should be implemented this here - https://github.com/bpoore/pbm-react/blob/master/app/index.js - since that file has a bunch of statusbar parameters, or if we should implement it on a per-screen basis or something. Are you able to make sense of this?

**Comment by bpoore** [comment]
I think it will go there in the index file, but not in componentDidMount because we will need to account for changes in dark mode preferences. I will look into this. Good find!

**Comment by bpoore** [comment]
@RyanTG, I think [this](https://github.com/bpoore/pbm-react/tree/status-bar) does what we want along with some cleanup / refactoring. The Android device I've been testing on is running really slow... I believe you've talked about experiencing the same issue. I hope it's not a concern with upcoming real builds! I wouldn't mind testing this some more, but overall, I think it's ready or really close to ready to be merged.

**Comment by RyanTG** [comment]
This was merged back in December.
