### ISSUE TITLE
Use Portland motd to show a notice on map

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#314]
As a way to communicate with users, we can have a banner/notice/message (not sure what to call it) that shows the Portland region’s motd. It can be dismissed by the user and not shown again until the text is updated by us. 

Is there already an RN or Expo module for this type of thing?

**Comment by bpoore** [comment]
@RyanTG, check out [this branch](https://github.com/bpoore/pbm-react/compare/app-alert) and let me know what you think.... it's just using our standard in-house confirmation modal to display the message text if the user hasn't seen it before. Do we want to be using the PDX MOTD for this? Is that not being used on the site at this time?  
<img width="325" alt="Screen Shot 2020-12-30 at 5 15 09 PM" src="https://user-images.githubusercontent.com/7720282/103389250-9642c080-4ac2-11eb-8333-9c5db66b0083.png">

**Comment by RyanTG** [comment]
For the record - since our slack will lose our chat: Awesome! And "yes, PDX!"
