### ISSUE TITLE
On Filter by machine, give users choice between all versions or one version

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#321]
Not really sure how this would look. I think it should default to all versions.
Maybe when they choose a machine, two radial buttons (or regular buttons) are visible on the filter screen that say "Filter for only this version" "Filter for all versions"

**Comment by bpoore** [comment]
Do we need to make an API update in coordination with the app? I believe the app is just passing over the machine_id in the request and if the machine has a machine_group_id, the API responds back with all versions of a machine. If that's the case, we will need to update the API to accept a flag that when set only sends back the data for a specific machine_id and not others in the group_id.

@RyanTG, what other priorities are we looking at here for our next release? If I started to look at the API implementation would that be a good use of time? No guarantees how long it will take me, but this seems like a potentially good small thing to get digging into the API a bit.

**Comment by RyanTG** [comment]
No other priorities! The two year stale notice would be cool, but that’s a minor issue.

Yeah, I think we would need an API update, so go for it!

**Comment by bpoore** [comment]
We are able to do this without updating the API. Here's the [branch](https://github.com/bpoore/pbm-react/compare/filter-by-version?expand=1). The button to select a version only shows up if you have selected to filter on a machine with a `machine_group_id`.

**Comment by RyanTG** [comment]
This looks great!

**Comment by RyanTG** [comment]
This has been merged, and I updated the 5.2.0 changelog.
