### ISSUE TITLE
If a location hasn't been edited in 2 years, then include a notice saying this

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#322]
In the location info: "This location has not been updated in over 2 years. The information may be out of date."

**Comment by bpoore** [comment]
I just pushed [this](https://github.com/bpoore/pbm-react/commit/05ea4c04addeb9b268c7bdfbc0b5188d034db778) straight to master. Have at it with styles!

**Comment by RyanTG** [comment]
I want to adjust the colors in dark mode.
