### ISSUE TITLE
On Location Details, can we put the heart button in the header?

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#330]
This is in the checklist, but I think it can be helpful to make a separate issue!

**Comment by bpoore** [comment]
Is this the desired outcome? Pretty sure we can make this work. I'm not certain I'm sold on it though. I kind of miss the sticky headers on LocationDetails and MachineDetails. I would feel better having the heart icon in the header if the scrolling content wasn't going under it.

![IMG_6143](https://user-images.githubusercontent.com/7720282/116466820-d2452280-a823-11eb-9ad0-3069a059d233.jpeg)

**Comment by RyanTG** [comment]
Yeah, twas my vision. I'm totally open to adding the header back into this screen. Though, like machineDetails, I don't think the header should have a title on it (because the text often doesn't fit).

**Comment by RyanTG** [comment]
This isn’t merged into master yet, right?

**Comment by RyanTG** [comment]
Changed my mind for now. Closing.
