### ISSUE TITLE
Missing backgroundColor on 'Successfully added location to your saved list' modal

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#332]
![IMG_6144](https://user-images.githubusercontent.com/7720282/116468068-459b6400-a825-11eb-841b-adfee2b3396d.jpeg)

@RyanTG, looks like it should be an easy fix, but looks like we are missing the `backgroundColor` for the button [here](https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L594). Wasn't sure what your vision is for the color values here, so leaving this for you to pick up.

**Comment by RyanTG** [comment]
Lol. Thanks! I'm still reviewing all the modals for styles. Thanks for catching this! I'll fix.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/335

I will still need to check this on my iPhone SE. That modal has some big margins...
