### ISSUE TITLE
On map marker callout, can we truncate the address?

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#342]
Similar to how we truncate the machine comments on locationDetails - https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L350 - can we truncate the address in the map marker callout? 

https://github.com/bpoore/pbm-react/blob/master/app/screens/Map.js#L69

The address is made up of four separate parts - `${marker.street}, ${marker.city}, ${marker.state} ${marker.zip}` - so I imagine we would need to first put those in a variable, and then check the length of that variable.

The issue is that the callouts have something of a fixed size, and there might be cases where addresses are super long. Plus, I don't think users always need to see the zip and stuff. At this point, I don't know when (how many characters) we should add the truncation. We could play with that.

**Comment by bpoore** [comment]
There's no reason why we couldn't do that. I briefly played around with how we deal with truncating text [here](https://github.com/bpoore/pbm-react/blob/501d2b3e9f24183a00a19b11d800922ca3bb0cef/app/components/LocationCard.js#L44), but got frustrated trying to get the wrapper stylings correct for it to work. Do you have a preference of which approach?

If you want to proceed with the initial plan outlined in this issue, do you want me to push up a branch with the address as a variable so you can play around with things?

**Comment by RyanTG** [comment]
I’ll play around with it first using the methodology in your link. Thanks!

**Comment by RyanTG** [comment]
Huh, even when I put `<Text style={{ marginRight: 20, color: '#000e18', marginTop: 5 }} numberOfLines={1} ellipsizeMode={'tail'}>{`${marker.street}, ${marker.city}, ${marker.state} ${marker.zip}`}</Text>` in map.js, there are still line breaks. Not sure what I'm doing wrong.

**Comment by bpoore** [comment]
That's what I was running into when I was messing around with it too. I think the issue is due to the styles being applied to the parent containers. I couldn't quickly figure it out at first, so held off waiting to see what your pref was.

**Comment by RyanTG** [comment]
I think we're fine for now. I just made the callout container a little bigger. If we ever encounter addresses that bleed outside of the container, then we can revisit this.
