### ISSUE TITLE
Include a machine image from OPDB on machineDetails screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#343]
Some machines on OPDB now include images. I would like to test out how it looks/feels to include one image (usually they are of backglass, I believe) on the machineDetails screen.

https://opdb.org/api

Example:
https://opdb.org/api/machines/GRVXD-MJN2n?api_token=xxxyyy

(I only have a token with my account. We probably want to create an OPDB account for pbm and use the token from that).

**Just checked with Andreas, and the below is not possible via the API:**
Future goal could be to allow users to upload a backglass image right to OPDB.

Create path: https://opdb.org/images/create?from_machine=119

**Comment by RyanTG** [comment]
```
grab a complete OPDB export on a regular basis and put the image urls in your database

as for the images themselves: Feel free to use the images directly from the OPDB server. I’ll be in touch if my provider suddenly wants a lot of money from me :stuck_out_tongue:

in the API response, but there’s one telling you which of the images is the “primary” image. That one has been picked by a human so you should just pick the “primary” backglass image and if that isn’t there grab the primary for whatever other category you want. In your case you probably want to go Backglass->Cabinet->Playfield->Other

Look for Export machines and aliases on this page https://opdb.org/api
that endpoint will give you a giant json document of all the data

```

**Comment by RyanTG** [comment]
First thoughts:

- Add OPDB API token to secrets in heroku
- Routine script that uses https://opdb.org/api/export?api_token=xxxyyy to export machines (once a week?) and then populates the omdb_img field with the url of the _primary_ image.

**Comment by RyanTG** [comment]
Shower thought this morning was that it can be tough to get full width images to size correctly in RN apps. Given that these images will be different dimensions from one to another, we may want to also create database fields for image height and image width (this data is in the OPDB API). Then, in the app we can do a calculation for the height like, "the _full_ width is x, but the width on this screen is now resized to y, therefore the height should be z."

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/1349

**Comment by RyanTG** [comment]
a start https://github.com/bpoore/pbm-react/pull/424

**Comment by bpoore** [comment]
@RyanTG, I couldn't push directly to your branch, but here is a new [branch](https://github.com/bpoore/pbm-react/tree/RyanTG-opdb_images) with the updated styles for images that don't stretch to the container as well as including a loading indicator. I really had issues getting the loading indicator to work correctly.... ultimately resolved it by adding an additional piece of state to the component which kind of feels like a hack, but it appears to at least be working well now.

Want to try this out before it gets merged to master? To see the loading indicator, I had to throttle my network speed.

https://user-images.githubusercontent.com/7720282/155905980-7ce1a046-d068-4937-a793-10f72f3665a5.mp4

**Comment by RyanTG** [comment]
FAQ:
How can I submit a backglass photo to the “machine details” screen?

The photos we display come from OPDB, and so you should upload your high quality photo using this form (must create an OPDB account). The photos you upload will not immediately appear in this app.

 https://opdb.org/images/create

General guidelines
OPDB needs photos of backglass/translite, playfield (full and details) and cabinet.

Backglass/translite guidelines:
Take photo straight on, not at an angle
Crop image to show only artwork
Avoid glare, if possible
