### ISSUE TITLE
Show number of machines on favorited map markers

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#354]
On the heart map markers, show # of machines.

**Comment by bpoore** [comment]
Would we need to move back to SVG for this? I initially imagine a SVG heart component where we are able to put text inside like we do for the other marker dots? I don't think we can easily put the # of machines on the heart image as it currently stands. I don't really remember why we backed out of using SVG in our first attempt with this- was it related to Android issues? We were never able to resolve the Android issues for the dynamic marker counts... so if that was the original problem, we could go back to make an SVG heart? I'll be thinking too, I just can't recall our history with how we ended up with the iOS marker dot we currently have.

**Comment by bpoore** [comment]
Maybe we could use the same approach as the marker dot, but use CSS to create a heart shape?

**Comment by RyanTG** [comment]
I'll have to review things, too. But, I thought that we could put text over a PNG marker (current heart marker is a png). If not, then yeah there are lots of heart SVGs out there. And I think we'd be able to use an SVG for the heart while still using a style View for the blue dots.

I belieeeeeve our current iOS marker setup is because the styled Views had the better performance than SVG. However, they might have both had the same performance (in iOS), but styling a view instead of an SVG just seemed simpler and so we went with that.

I remember it being pretty easy to put numbers on top of markers.

**Comment by bpoore** [comment]
How's [this](https://github.com/bpoore/pbm-react/compare/numbers-on-heart-marker-ios?expand=1)? This was just quick and dirty, but seems to work!

**Comment by bpoore** [comment]
It makes the heart sizes variable based on number of machines on location as well... not sure if we want that or not.

**Comment by RyanTG** [comment]
I haven’t looked at this yet. But note that the hearts are on Android, too. The assumption is that people aren’t hearting 80 spots close to each other and so it won’t impact performance.

**Comment by RyanTG** [comment]
But I guess we don’t need to show the numbers on Android given that none of the other markers on Android show numbers.
