### ISSUE TITLE
Feature Request: Landscape Mode on iPad

### ISSUE THREAD

**Issue by newcrunchysue** [bpoore/pbm-react#356]
Landscape mode would be super nice. Thanks.

**Comment by RyanTG** [comment]
I agree that it would be nice on iPad. One issue is that landscape mode doesn't work/look great on the phone (last I checked) and (again, last I checked) it's not possible to have landscape/portrait modes available for tablets without also enabling it by phones. But we'll keep monitoring this.

In any event, we already have an open issue for this! https://github.com/bpoore/pbm-react/issues/229
So I'm going to close this duplicate.
