### ISSUE TITLE
Add "kilometers" option to Settings

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#365]

**Comment by bpoore** [comment]
If we want to go all-in, we can use the km for event search as well in the IFPA API:
https://www.ifpapinball.com/api/documentation/calendar/

Throughout the rest of the app, we'll replace the 'mi' references with a calculation that is aware of the user's selected option.

**Comment by RyanTG** [comment]
Yeah, I think it would be good to go all in here, just so it's consistent for the user throughout.

**Comment by bpoore** [comment]
[Branch](https://github.com/bpoore/pbm-react/compare/mi-and-km?expand=1)
