### ISSUE TITLE
On the submission form, the country field is not using the correct values

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#369]
I'm struggling to nail down the exact issue here. From what I can tell, when users select a Country in their location submission, the value does not match what we're using in our country_select gem on the website. And so when admins approve the location, the value in the country field gets emptied. (see my recent comments on https://github.com/scottwainstock/pbm/issues/1162).

I have to manually look at all the approved locations (that admins approve, and don't realize what is happening), and then I fix the field. But this takes work, and it would be nice if this was fixed.

I think the issue is that when a user selects, for example, "United States", that is what gets added to the submission. However, we actually want it to use the country code, "US".

**Comment by bpoore** [comment]
I don't remember off the top of my head where we got [the country codes](https://github.com/bpoore/pbm-react/blob/master/app/utils/countries.js), but we could certainly adjust. I will look into the gem being used to see if we can just update our country list to match. Perhaps there is a node package with the same format we could/should be using.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/372/commits/951e9467272cbd89620df15fdb0b172a3e46a57f
