### ISSUE TITLE
Profile - screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#38]
Contents:

````
Profile

Username

Member since: date

Machines added: #
Machines removed: #
Machine comments: #
Locations submitted: #
Locations edited #

Saved locations (link to the saved page, I guess)

Locations edited (only show last 50)

High scores:
Score on Machine at Location

Logout
````

**Comment by RyanTG** [comment]
The "Saved Locations" link doesn't work for me. It doesn't go anywhere. I didn't get a chance to dig into why that might be.

**Comment by bpoore** [comment]
@RyanTG, are you still seeing this? When I try to reproduce with the simulator or on my iPhone, pressing the button takes me to the favorite location screen.

**Comment by RyanTG** [comment]
Now it works! Magic..
