### ISSUE TITLE
Android: heart markers not always rendering correctly

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#382]
On Android the custom markers (the hearts) are partially transparent when I first load the map. Moving the map and reloading the results causes them to then render correctly. But sometimes reloading results will cause only one to render correctly, and then another one renders correctly the next time I reload. So, sometimes it takes multiple reloads to get them all.

Sometimes I notice the regular map marker loads first, then disappears and is replaced by the heart. The heart fades in, but sometimes stops midway - and so it's super faded.

So, maybe this has something to do with how we're loading those hearts...

Beth sez: Looking at the code, there's a lot of stuff I don't really understand or remember why it's there... specifically, the tracksViewChanges in our MapView.Marker. I suspect we tried something to make performance better, but we might be doing something wrong with that.

Maybe something here or linked here https://github.com/react-native-maps/react-native-maps/issues/2083

**Comment by bpoore** [comment]
I wasn't able to specifically reproduce the transparency issue with the Android hearts, but on master I was seeing if you un-heart  a location, the re-heart, the heart was not initially showing at all. I tried just removing the tracksViewChanges stuff we talked about before and that at least fixes the issue I can see. 

Lemme know what you think / if you can still see transparent [hearts](https://github.com/bpoore/pbm-react/compare/android-hearts?expand=1).

**Comment by RyanTG** [comment]
Thanks, I’ll check!

**Comment by RyanTG** [comment]
So far so good! I'll keep checking on it (because it's kind of random). But so far I can't replicate the issue on that branch.
