### ISSUE TITLE
Change entry point from index.js to App.js

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#384]
I’m looking toward the future when EAS will be free and available, and we may want to use it. When I briefly tried EAS back in May, we got an issue due to our app using a “custom” entry point (the index.js file) instead of the default App.js entry point. I posted a thread about it - https://forums.expo.dev/t/managed-eas-build-failed-for-both-ios-and-android/52413 - and there were some possible work arounds shared, though I couldn’t get them to work.

I then assumed this issue would get fixed, given that a lot of apps probably use custom entry points. But so far, according to a reply posted last week, it hasn’t been. So maybe it won’t ever get fixed, and the solution for us will be to not use a custom entry point.

So that’s what this issue is.

In the meantime I’ll do more searching in the Expo forums to see if others have faced this same issue.

**Comment by bpoore** [comment]
https://github.com/bpoore/pbm-react/commit/fc2d94fae2f7b0c750e203bd2a3ff05f91b13470
