### ISSUE TITLE
Store keys in a gitignored file

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#388]
About once a year I make the mistake of committing the gmaps api key. 
It's a burden to have to continuously remove and re-add that key. It would be really great if we could store it in a separate file.

We're supposed to use secrets for stuff like this https://docs.expo.dev/build-reference/variables/
But there was a reason why we couldn't... but maybe we can if we revisit it.

**Comment by bpoore** [comment]
We can revisit this. I didn't realize it was an issue. The file we are using currently is not under version control, so I'm a bit confused how it would keep getting committed. I recall the original problem relating to not being able to interpolate values into app.json as json doesn't allow for that. At the time, that did seem odd as I assumed there was a more robust way to deal with secrets. I will look into this... it is something I have wanted to revisit as our current solution is definitely not typical compared to other JS projects I've worked on.

**Comment by RyanTG** [comment]
> The file we are using currently is not under version control, so I'm a bit confused how it would keep getting committed.

The file I have to add/remove the key from is app.json, which is under version control. Each time I make builds I have to add the key to that file, then I remove it (replacing it with the word “key” in three places). 

In practice, this means manually  adding/removing it from this file many dozens of times a year. And every 50 or so times I make a mistake and accidentally leave it in with a commit.

**Comment by RyanTG** [comment]
That Expo Variables link above appears to be for EAS, and might not work for `expo build`. Furthermore, the doc doesn't show you how to access the variable (is it simply `$name_of_variable`?

A Canny issue here, which says it's resolved, and also doesn't clearly point to the solution. https://expo.canny.io/feature-requests/p/environment-variables-in-appjson

**Comment by bpoore** [comment]
@RyanTG, I'd like for you to play with [this](https://github.com/bpoore/pbm-react/compare/dotenv?expand=1) before it gets merged. It's working for me locally, but I'd like for you to create a build to make sure everything is working as expected outside of the dev environment. 

To test this out, you will need to make a .env file at the root of the project and populate it with what is in the env_template (adding in the real keys). You may need to run `expo r -c` to get the project running locally for you due to the changes in the babel.rc etc... I'm not certain. I had to while working on this.

**Comment by RyanTG** [comment]
Sweet, I’ll make an Android apk and will test. Can’t do it until at least tomorrow.

I see a deleted reference to `app/config/keys.js`. I don’t think I have that file in my project (not at my comp rn)! Um, was that where I was supposed to be storing keys? 😇

Thanks for figuring all this out. I didn’t even understand that app.config.js _replaces_ app.json.

Once this and the new App.js entry is in master, then I think we’ll be in a good position for EAS. EAS requires you to have a clean branch before creating a build, which means that we would have had to commit our secret keys, build, and then revert that commit before pushing to github. Huge hassle!

**Comment by bpoore** [comment]
I'm sure you definitely do have a `app/config/keys.js` file 😄  The issue with the app.json file + keys is that you can't interpolate variables in a json file. It was off my radar that you were manually plugging in keys for every build, so my apologies for not prioritizing getting something figured out for this sooner! After switching to app.config.js, we could have kept the `app/config/keys.js` file in place, but moving things to a `.env` file is much more aligned with how projects are more typically structured... so there are some technically unnecessary changes in this branch, but to ourselves and other potential contributors, this is all far more conventional now.

**Comment by RyanTG** [comment]
I builded an apk and sideloaded it onto my Android 11 device. Map loaded fine - no errors. I think that's all I need to check for.

Related to this - https://github.com/bpoore/pbm-react/issues/390 - we should figure out where to point the key for geocoding, if that's what the geocoding issue is.
