### ISSUE TITLE
On Search, keyboard is sometimes dismissed. Caused by spacing; no results?

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#390]
I've noticed this, and I can replicate it. But I can't figure it out. Even after removing all the "keyboard dismiss props" it still occurs.

Steps:
1. Click the search bar
2. Search "Diver " (with a space after)
3. Wait for results to load
4. Then click backspace. At that point, the keyboard gets dismissed.

You can also replicate it by typing "Diver" (no space), waiting for results to load, and then adding a space. The space causes the keyboard to get dismissed.

There are, of course, other ways to replicate it.

The issue is annoying because sometimes I make a typo in my search, and I want to backspace and fix it, but then the keyboard keeps getting dismissed when trying to fix the typo!

Maybe it's because "no results" causes the keyboard to be dismissed? Because "Diver " with a space produces no results...

Again, the issue persists even after removing both keyboard things here: https://github.com/bpoore/pbm-react/blob/master/app/components/Search.js#L295
So I don't think it's caused by those.

**Comment by bpoore** [comment]
@RyanTG, check out [this](https://github.com/bpoore/pbm-react/compare/search-bug?expand=1) and let me know what you think. I suspect over time, we updated react-native-elements and missed some new behavior for `Input` components? I was remembering why we implemented things like we did originally- as a refresher, we want to be searching from the API primarily and only give the option for the user to explicitly have their search geocoded if their results turned up no results. On master, when the keyboard is currently disappearing is when we previously were updating the appearance of the search button... currently our attempt to update it, just hides the keyboard. 

The change in my branch makes it that we always show a search button... but the only time a search is geocoded is still only when the user's search had no results. Testing locally, I am getting a request denied error when trying to geocode a search. I tried on the production app as well with the same result. I had to make a google maps geocoding API key to get geocoding to work. I believe this costs $$ to use and why we originally were trying to limit the number of geocodes individuals do, but this is definitely broken currently. We need to add another google maps API key for geolocation, or if we don't want to offer that anymore, we need to pull this functionality out. 
![IMG_6401](https://user-images.githubusercontent.com/7720282/132998873-26ec4b55-8f21-4952-a10b-0e165e39b692.jpeg)

**Comment by RyanTG** [comment]
I think we do want to geocode when there aren’t any results. We discourage it (via search results), but we don’t want it gone completely. I totally thought this was working! We have the api key in there in three places, and I thought one was for this.

We can use the same key. It only costs money after a buttload of queries. We use this same key on the website and never go over.

**Comment by RyanTG** [comment]
I just tested the branch. Looks good!

We didn't make a decision at some point to not include any geocoding for searches, did we? I'm guessing no, given that we are showing that geocoding error.
