### ISSUE TITLE
5.2.7 Design Issues

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#391]
Notes for myself:

- [x] Location Details: has website but no phone, "last updated" should be narrower. Check "B*rcade LA"
- [x] Quick button border in dark mode. or try another color (blue1 ?)
- [x] Icons on location card?
- [x] Line break on search
- [x] Adjust color of logout/login button
- [x] Weird transparent borders on android
- [x] Location type box is super wide on ipad
- [x] Recent activity font? Currently bold. Maybe that’s ok
- [x] Check on search screen input text color
- [x] "Family Fun Center" can take up two lines. See All Amusement Fun Center. Adjust width of meta accordingly.
- [x] Right margin on machine comment on locationDetails
- [x] Last updated narrow width is still not right. See Momo bar

**Comment by RyanTG** [comment]
5.2.7 Changelog thus far:

- Fixed issue with deep links not always working correctly (actually in 5.2.6 but we forgot to mention)
- Updated theme colors, as well as redesigned some elements, especially on the Location Details screen
- Replaced system fonts with custom fonts
- Android: Fixed bug with heart map marker icons not always displaying correctly
- iOS: Switched back to using Apple Maps instead of Google Maps
- Fixed issue with search not geocoding correctly
- Fixed issue with search keyboard being dismissed at wrong times
- Code refinements and other little tweaks

**Comment by bpoore** [comment]
I would love to get the splash screen animation as part of our next release, but as we agreed, to make that the best experience, we will be messing around with updating the root screen of the app. We will want to do some thorough testing after that work is done as the location of our logic for deeplinks, etc will be getting moved. If we are wanting to get this into the next release, I will try to prioritize getting the work done in the next couple days, but it will be a non-trivial set of work we would be introducing to the app. What are your thoughts on the release timeline? Would you like to wait on the splash screen upgrade and if so, if that means we are at least a week out from releasing, is that ok with you?

**Comment by RyanTG** [comment]
I'm definitely ok with at least a week out from releasing. And I understand that it's non-trivial and that we should thoroughly test the deep linking and stuff.

As far as _animation_, I haven't looked too deeply in that. Are you referring to anything specific here, like a fadeout? Or something cooler, like the ball growing/shrinking in size? Either way, I'll look into it.

I'll start here.
https://github.com/expo/examples/tree/master/with-splash-screen

**Comment by bpoore** [comment]
Animation was the wrong word... if you want to play with further animations, then by all means after I get things working, go ahead. Some of the things you just mentioned sound pretty cool! I was meaning just the prolonged splash screen showing. I guess that's not an animation, sorry!

**Comment by RyanTG** [comment]
Okay, phew! 😛
Actual animations would be cool, but they’re a little intimidating. Probably easy to do something simple, though.

**Comment by bpoore** [comment]
Hahaha... sounds like I gave you the palpitations I get every time we talk upgrading react-navigation.

**Comment by RyanTG** [comment]
I think the design is ready for screenshots now, so I'll work on those soon.
