### ISSUE TITLE
Save Locations - screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#40]
Saved Locations screen that is styled just like the LIST view of locations. Shows all the locations you've saved.

**Comment by RyanTG** [comment]
“You have no saved locations. To save your favorite locations, lookup a location then click the heart icon.”

If not logged in: “please login to start saving your favorite locations.”

**Comment by RyanTG** [comment]
When viewing location details, have a "HEART" icon hovering over the map container. If you click the heart, the icon gets filled in, and a modal/toast comes up, and the location is added to your "saved locations" list.

If you click the heart icon again, the location gets removed from your saved list.

If not logged in, heart icon is not visible.

**Comment by bpoore** [comment]
@RyanTG, the Saved location screen is blocked for a bit while the API response gets updated with the info we need. In the meantime, users can add/remove locations to their list from the location details screen: a499b4440c453e2b896bd06a90406062592e05bd

**Comment by RyanTG** [comment]
Totally fine. I had only thought about how to add the heart icon to the location details screen. I hadn't thought of how to add it to the location list. So this gives me time to think.

**Comment by RyanTG** [comment]
> While fixing that, I can make the saved sortBy index match the way this screen is behaving if you like how this screen acts?

Yeah, I like how it's saving the sortby index. So, go for it!

> Do you think we should add the ability to remove a saved location from this list screen? I kind of imagine sliding left to reveal a delete button possibly?

Certainly would be cool, but I also don't think it's a priority since users can currently click on a location to view the details, and remove it there. I'd say, if you FEEL like doing a left slide action, then have at it. But if not, then that could wait for a later release.

Not sure if it's just me, but if I click on a location to view the details, it just spins. The location details don't load (but they do load if I click on the location from the map). Do I need to `npm install` for this commit?

**Comment by RyanTG** [comment]
There's a chance that sometimes the "distance" isn't sorting correctly when I first load it. Could be from me constantly refreshing expo, though. I'll keep testing.

**Comment by RyanTG** [comment]
AWESOME! 

I think this is a really really great update. I think a lot of people will be using it.

**Comment by bpoore** [comment]
@RyanTG, I believe this should be good to go now. We just need styling for the text when a user has yet to add a favorite location.

**Comment by RyanTG** [comment]
ah yeah. I'll do that soon.
