### ISSUE TITLE
Suggest Location - screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#41]
Form. If user is not logged in, content:

````
Suggest a New Location

But first! We ask that you Login(link). Thank you!
````
If logged in, content:
````
Suggest a New Location

Add a new location to the database. Fill in this form. We'll review it to make sure the data works... so don't expect it to show up just yet. Thanks for helping out!

form:
- Location Name (text field)
- Street (text)
- City (text)
- State (text)
- Phone (text)
- Country (LIST)
- Location type (LIST)
- Operator (LIST)
- Comments (text)
- Machines (autocomplete, and you can add multiple machines, separated by comma)

Submit button.
````

**Comment by bpoore** [comment]
Think this is ready for a last bit of styling and review @RyanTG.

**Comment by RyanTG** [comment]
I made a few little changes. https://github.com/bpoore/pbm-react/pull/128/commits/356f55861068827971b8d2b0bd8d5612f8008b09

I think the form should not be submittable if there are no machines selected. On the preview screen, if there are no machines, we can include an error text that says "please select at least one machine" and the submit button should be greyed out until there's a machine.

I changed the phone field so it's not only numeric, so people can add dashes.

Is there any way to force the first character in the website field to not be capitalized? Our phones tend to capitalize the first character you type. In that case it'll be "Http". But that actually messes up the website field because we have a script that looks for the existence of "http://" and adds it if it's not there. So when it sees "Http" it still thinks that "http" is not there, and it adds it, resulting in "httpHttp://..."

the machine selection with the Xs is awesome! I didn't test clicking the Xs. I'll do that.

**Comment by RyanTG** [comment]
Notes: The submissions are going to the Portland region right now, but they shouldn't. They should go to "regionless". Eventually we want to set up bounding boxes that tell us the boundaries of a region, and then if that submission is within a bounding box, the submission should go to the admin of that region. Bounding boxes are something @scottwainstock has to set up (see https://github.com/scottwainstock/pbm/issues/1089).

Also, the submissions aren't being "geocoded", but they should be. We have it set up so that after the submission is sent, the address gets automatically cleaned up and a lat/lon gets generated. When the admin views the submission in the submission queue, they see this cleaned up version. I don't know how to set it so that the submissions from the app go through this validation/geocoding process. Scott could help here.

**Comment by RyanTG** [comment]
Oh, I see that it does require a machine. The error it's showing is `Region, location name, and a list of machines are required`. which, yeah I guess that's an error for a regional location submission than a regionless one. But even if it was supposed to be a regional submission, it should never say that a region is required, since users can't add that in that field. But I guess that's something we need to change on the website.

**Comment by bpoore** [comment]
Yeah, the error message you saw was coming directly from the API. We need to update the wording for the error message here after migrating to regionless.

I’ll look into the geocoding that’s happening after a submission, I wasn’t aware that was happening.

This will remain in a pending state until we can get the regionless endpoint figured out / have the region requirement removed. The geocoding that I had missed should make the determination of where to send the info pretty painless once that’s in place.

**Comment by RyanTG** [comment]
I think this is settled. But I still need to add the radius values in admin. PLUS we need to push this feature to staging. https://github.com/scottwainstock/pbm/issues/1089

**Comment by RyanTG** [comment]
Correction: the radius values are on the staging server. So, Scott is envisioning that the lat/lon being passed with the submission is the user’s current lat/lon. I was envisioning that the lat/lon would be the one geocoded from the submitted address. We’ll eventually have to have the latter functionality on the website, but for now on the app we can go with Scott’s plan. 

I can help with testing it.

**Comment by bpoore** [comment]
@RyanTG 21bad65bc044014a85a6b9c4a25a7f9f9064bd0 now includes the user lat/lon with a location submission. I think this is ready for testing. Let me know if there's anything I can do to help with that. I confirmed the email is coming through after a submission- looks like lat/lon aren't included fields on the email going to an admin which is fine, just let me know if the values aren't coming through properly.

**Comment by RyanTG** [comment]
Last thing to fix on this is the geocoding. When locations are submitted, they should be geocoded _prior_ to landing in the admin submission queue. I'm not sure exactly how it does that. But it has something to do with the api.

Me:
```
When we submit locations via the new app, beth has the user lat/lon attached, which makes the submission go to the correct region - great! but, the submission isn't being geocoded/cleaned up - do you know why that could be?
```
Scott's reply:
```
I'd need to see an example of what data is being sent.
app/controllers/api/v1/locations_controller.rb:31
is where it goes
app/controllers/application_controller.rb:47 is what gets called to save the location suggestion.
All the lat/lon thing does is pick the region.
app/controllers/application_controller.rb:81 is where the Geocoder stuff picks up.
So maybe some test data I can run through the backend?
```

**Comment by RyanTG** [comment]
Status Update: there might be an issue with the API and/or the staging server, causing location submissions to not geocode.

**Comment by RyanTG** [comment]
Geocoding is fixed. Issue was that the staging server didn't have an API key.
