### ISSUE TITLE
Blog screen is crashing app in Android

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#439]
Podcast link is _not_ crashing app! Only blog (in my test). Very strange. Expo is not showing me a crash log so at the moment I have no idea.

**Comment by bpoore** [comment]
I was able to reproduce with both the blog and podcast screens on a simulator. Found [this](https://github.com/react-native-webview/react-native-webview/issues/811), adding the prop androidHardwareAccelerationDisabled={true} appears to fix the issue. Pushed a [commit](https://github.com/bpoore/pbm-react/commit/6a2735d2628155027823b56a3856fa70bfce25d6) directly to master.
