### ISSUE TITLE
FAQ - screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#45]
This is the current FAQ https://pinballmap.com/faq

But we should update this.

Content pending...

**Comment by RyanTG** [comment]
FAQ Content (work in progress):

**How do I add a new location?**

Click the menu icon in the lower left, and choose "Add Location". Then fill out the form! We moderate the submissions, so it will a few days for the location you submitted to be added to the map. The more accurate and thorough your submission, the quicker it will get added! Make sure to include at least one machine with your submission.

**This machine is no longer at this location.**

This is a user-powered map, and YOU can remove the machine from the location. Click on the machine name, and then look for a "remove" button.

**This location closed/no longer has machines.**

Simply remove all the machines from it. Empty locations are periodically removed.

**Have a question that we didn't cover here? Ask us!(link to contact page)**

**Comment by bpoore** [comment]
Assigning to @RyanTG, believe this just waiting for content at this point.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/68/commits/55236eaef8cda222f467f4de1273d835662607fd
