### ISSUE TITLE
Podcast - screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#46]
Image: https://pod.pinballmap.com/wp-content/uploads/2018/07/mappin-logo-500.png

Text (will probably edit this): Please enjoy Mappin’ Around w/ Scott & Ryan, a podcast about Pinball Map!  We’ll release a new episode once a month. 

Link: https://pod.pinballmap.com/

**Comment by RyanTG** [comment]
@bpoore I just created "placeholder" screens for the 3 of the static pages (basically, screens that I can probably do entirely on my own). https://github.com/RyanTG/pbm-react/commit/9f8bf64ec3654360590961ed99d50539ae579bf2

Can you tell me if this stuff is needed? It's on each one, but I'm not really sure what it does. Saves a state or something?

````
import { connect } from 'react-redux';

const mapStateToProps = ({ machines }) => ({ machines })
export default connect(mapStateToProps)(Podcast);
````

**Comment by bpoore** [comment]
That is necessary for components using the the Redux state.  mapStateToProps is getting the pieces of state we need for our component allowing for us to use those pieces of state as props being passed into the component. When there is mapDispatchToProps function, that allows for us to use functions in the component to update / change the Redux state. We can talk more about the details or I can send some resources your way if you're interested in learning more!

**Comment by bpoore** [comment]
Assigning to you @RyanTG. I think this page just needs styles and text now.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/68/commits/82d9998733c129a0f244a6b7e20f8488f9dbada6
