### ISSUE TITLE
Surface notification to user who tries to perform a write action when they haven't confirmed their account

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#49]
Noticed upon clicking confirm location is up to date with a new user, no update occurs / no notification. The API is providing a response to allow us to provide a meaningful notification to the user rather than just not doing anything: 
<img width="1277" alt="screen shot 2018-10-10 at 1 10 25 pm" src="https://user-images.githubusercontent.com/7720282/46763278-39168680-cc8e-11e8-8b83-8aa25de2c8d9.png">

**Comment by bpoore** [comment]
@bpoore

**Comment by bpoore** [comment]
@bpoore

**Comment by bpoore** [comment]
@RyanTG, I've started to go through adding in error handling so the app doesn't just hang or not provide context if an action the user has tried didn't work. This could use refinement over time, but it seems to be a good start 8a86498b.

What I've been working on covers the issue I made here, but we might be missing something in the flow when a user creates an account on the app. Currently, we log them in immediately since the API is returning their credentials, but before they are able to have any privileges of a logged in user, they must confirm their account first. 

Do you want to stick with immediately logging them in or should we change that? At this point, if they try to do a put/post/delete action, the confirmation modal will pop up with the error from the API saying 'You have to confirm your account before continuing', so that's good. Before, their actions wouldn't occur and they weren't being alerted why. What do you think?

**Comment by RyanTG** [comment]
I think the current behavior makes sense.

I think I need to give all the screens a look over and style the errors when necessary? I've seen error section here and there, and sometimes I've ignored them because I wasn't sure what would prompt the error.
