### ISSUE TITLE
Add a map movement tolerance so results don't refresh if you nudge the map

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#51]
If this is possible (I saw this on the Zillow app): if you just _slightly_ move the map, then the results shouldn't refresh.

We can figure out the definition of "slightly."

**Comment by bpoore** [comment]
There's still a lot of thought that can go into this, but this looks to be a major improvement already
058d6156baa0295f922fb5002d266f1dfe0271e1

**Comment by RyanTG** [comment]
Wow, it's the simple things...

Yeah, even though the "loading..." message still shows up for a second, that's fine. Important thing is that the pins don't totally refresh each time you nudge the map. I'm fine with closing this unless you want to dig into it more.

**Comment by bpoore** [comment]
Sure we can close this out. 

Would you prefer to ditch the loading indicator? I could go either way on this personally.

I think in the long run, we don't necessarily need to be making a new request every time there is map movement... I think we could be doing calculations to determine if we need to make a request or if moving the map without adjusting the locations would be fine. 

...basically, there's a lot we could be doing with this eventually. How much that matters currently, probably not much.

**Comment by RyanTG** [comment]
No, I like the loading indicator. And I’ll see if I can adjust it in android.
