### ISSUE TITLE
Edit Location Details - Screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#58]
Add an "Edit" button to the right side of the header on the Location Details screen

When clicked, it opens a new screen where you can edit:

- Phone number (text box)
- website (text box)
- operator (dropdown)
- location type (dropdown)
- location description (bigger text box)

Edit button not visible if user isn't logged in.

**Comment by bpoore** [comment]
Starting to work on this. The behavior of the old iOS app updates one field at a time without a save confirmation. Is the preference here, to have the above fields editable all at once with an option to save/cancel all edits at once? Happy either way, just messing around on the current app, this reads as different behavior. 

To confirm- all the attributes other than address should be editable?

**Comment by RyanTG** [comment]
> To confirm- all the attributes other than address should be editable?

And Location Name isn't editable, either.

> Is the preference here, to have the above fields editable all at once with an option to save/cancel all edits at once?

My preference is to have them all editable at once. That's how it is with Android. I think it results in less clicking for users. I don't love how the current iOS app functions/looks there.

**Comment by RyanTG** [comment]
On the picker, if you choose the top "none" item (where there are no words), the preview shows "none selected" - which seems good. But after you click the "confirm" it doesn't actually change the selection to none. Instead it just keeps whatever was in there before.

Do we need something like this? https://github.com/bpoore/pbm-react/blob/master/app/screens/FilterMap.js#L71
But it's a "none" choice. And if you choose none, then the location details screen won't show anything. So there would be no location_type_id or operator_id for the location after you've chosen none.
