### ISSUE TITLE
Remove labels from TabNavigation menu

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#61]
Making a bug of this. I can't figure it out... should be really simple to remove the labels, but I'm not able to make it happen!
<img width="248" alt="screen shot 2018-10-13 at 6 01 47 pm" src="https://user-images.githubusercontent.com/7720282/46911499-4e9be280-cf12-11e8-80cd-f081ef72d7da.png">

**Comment by RyanTG** [comment]
I think it's fine to have labels. I think we can close this.

**Comment by bpoore** [comment]
Sweet. Closing.

**Comment by RyanTG** [comment]
These did it: https://github.com/bpoore/pbm-react/pull/71/commits/3297b79a1fb2394d4acc2f9c0140caac3926e669
https://github.com/bpoore/pbm-react/pull/71/commits/6db95dfb33862c6a2492f8984f01ea3204c9b63a

**Comment by RyanTG** [comment]
For reference https://stackoverflow.com/questions/49013084/how-to-show-tabbar-label-only-on-active-tab
