### ISSUE TITLE
Add logout / login affordance to drawer menu

### ISSUE THREAD

**Issue by bpoore** [bpoore/pbm-react#62]
Drawer menu has been implemented, but we need to have a login / logout button at the bottom of the menu. Currently the drawer menu isn't smart enough to be aware of the user's login status. Need to consider how to go about adding this functionality.

**Comment by RyanTG** [comment]
If we're low on space we can probably ditch that "Blog" menu item, since that screen might not be added to the app.

**Comment by bpoore** [comment]
This was a real PITA to figure out. 4f6151ff4e2aa81e29298ef416eb7ac4ce4c5799. In order to access the redux state to know if a user is logged in or not to offer them the correct option, it was necessary to make a DrawerMenu component where the login / logout is separate from the rest of the drawer items. Everything is work well now, but we need to style the login / logout part of the drawer: 

<img width="386" alt="Screen Shot 2019-04-02 at 2 06 44 PM" src="https://user-images.githubusercontent.com/7720282/55436225-91995300-5550-11e9-9741-7410bbca2105.png">
