### ISSUE TITLE
Do we need the "Submit" button on the searchbar?

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#64]
Investigate solutions for removing it.

If impossible, would it be better to use a "search" icon? Probably not..

**Comment by RyanTG** [comment]
I made an icon for now...

**Comment by bpoore** [comment]
It looks great!

**Comment by RyanTG** [comment]
Feedback I’ve gotten is “I don’t think people are going to know that this means “submit.”  

So we should still aim to have no submit button, and instead make users hit return on their keyboard.

**Comment by RyanTG** [comment]
Wasn't totally clear to me why I left this open. But it's because:

`And it would still be nice to have the keyboard "return" also submit the form.`

**Comment by RyanTG** [comment]
And actually, on iOS at least, when you backspace all the characters from the searchbar, the keyboard is still visible. The only way to minimize it is to click the "Return" key. So maybe we don't want the return key to submit the form, given that we need that key to minimize the keyboard.
