### ISSUE TITLE
Display content from blog on Blog screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#67]
Can we pull the html from the blog and plop into into the app?

Would we need pagination?

**Comment by bpoore** [comment]
We might be able to lock in the dimensions better, but just a quick search turned up this and is pretty decent! b5bebe324fc5ad3aef26e23f543cbd8aceaf754c

**Comment by RyanTG** [comment]
It took a little while to load while on a mobile network. I'll update the blog so that it only displays like 2 or 5 posts per page. It might be at 10 posts per page right now.

**Comment by RyanTG** [comment]
I changed the blog to display 5 posts per page (it was set to 15 before). This will speed up loading.

Do you think we should also add an ActivityIndicator?

The WebView concept is funny! A user could potentially click on a link on the blog, and then just browse the web through the app.

**Comment by RyanTG** [comment]
I changed the blog to display 5 posts per page (it was set to 15 before). This will speed up loading.

Do you think we should also add an ActivityIndicator?

The WebView concept is funny! A user could potentially click on a link on the blog, and then just browse the web through the app.

**Comment by RyanTG** [comment]
Added an activityindicator: https://github.com/bpoore/pbm-react/pull/165/commits/697a4f09f0eb91e4d8cdebaea3a25d16810c1e8a

Taken from https://stackoverflow.com/a/48492443

If this is not how you'd like to do it, lemme know.

Still not the fastest load.

**Comment by bpoore** [comment]
Interesting!

I wasn't ever seeing the Activity Indicator, but moving the piece of logic above the WebView worked. Good call to get that put in here. 4c54ea0d751f788b6ea32ea18b6d7c36fc995865
