### ISSUE TITLE
Include "Reset" Button on filter page, and on map if there's a filter applied

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#79]

**Comment by bpoore** [comment]
7fcd076ddeb624106996f951e7dfe5ced6ae7885

Still working on getting the operators added to the filters screen, but we can now clear applied filters. Button could use some stylin' love.

**Comment by bpoore** [comment]
Oops, I missed adding a clear filters button on the filter screen. Here is a commit with a button 88cd0a1c0ceba85c328d2c74a7a20e63a2fede20. I used the WarningButton component... feel free to update with a different look / feel and let me know if this doesn't appear to work correctly!
