### ISSUE TITLE
Location Details - machine list: show year/manufacturer of machine

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#9]
In the "location list" view, the year/man is included, but in the location details for an individual location, it's not (instead, it just lists the machine name). Ideally, we'd be able to style man/year differently than the machine name, but if that's not possible/easy, then that's ok.

Stylewise, I'm thinking:

**Machine Name** _(Man, Year)_

**Comment by bpoore** [comment]
This was an easy addition. I just pushed it up. Considerations we might need to have- what the format should be if the manufacturer and/or year aren't available. What I put up will end up looking weird if either of those fields aren't present.

**Comment by RyanTG** [comment]
I was about to give some ideas... but then I looked and saw that 0 machines are missing a year or man.
So, let's not worry about it?

**Comment by bpoore** [comment]
Great! Closing our first issue ticket :)
