### ISSUE TITLE
Add Score & Add Condition modals - add text to describe the context

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#98]
I tried to do this myself, but struggled with getting the variables set up.

I think it would be nice to have text titles on the modals, just to remind people what they're doing...

For machine comment:
"Comment on [machine.name] at [location]"

For Add Score:
"Add your high score to [machine.name] at [location]"

**Comment by bpoore** [comment]
@RyanTG needs styling, but the data is set up cd26b6360bc84b5006bf9eeebf28caab54547acf

**Comment by RyanTG** [comment]
Thanks!
